### ISSUE TITLE
Write info about skipping a job to channels

### ISSUE THREAD

**Issue by SteffiStuffel** [digitalfabrik/integreat-app#2304]
Lately we forgot to unset the "SKIP_JOB_PROMOTE_INTEGREAT_IOS variable and Integreat was not updated for a few months. To prevent this in the future and to be more transparent, I suggest we write a message to ~releases or ~tech-react (to project channels may be to much effort for the benefit), so we (and everyone else) gets informed that a promotion or whatever is skiped.

**Comment by steffenkleinle** [comment]
In my opinion this should go to ~integreat-app-notifications for integreat and perhaps a new channel ~lunes-app-notifications for lunes
