### ISSUE TITLE
Page based offer

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2313]
**Is your feature request related to a problem? Please describe.**
In the future we want to move offers into our page based content to avoid parallel structures and get rid of the "Offers" menu in the app.

**Describe the solution you'd like**
When fetching a page, there is an additional field `offer` which contains on single item of the offers endpoint. The offer should probably be positioned below the actual page endpoint.

**Describe alternatives you've considered**
N/A

**Additional context**
- https://github.com/digitalfabrik/integreat-cms/issues/2360

**Comment by steffenkleinle** [comment]
@sarahsporck do you think we still need a design for this?

**Comment by sarahsporck** [comment]
Hmm. Probably yes. The question is where and how the offer is displayed. Does it directly flow into the content? If it is below the content, as described in the text, do we just pin it below? Do we still use the tile here? What about Offers like sprungbrett? To me these are mostly design/usability questions. But we could also spend some time and discuss this in the team.

**Comment by nikolahoff** [comment]
[Here](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=1936%3A81&mode=design&t=PlawIftw1YKKESb0-1) ist the link to the figma file.
