### ISSUE TITLE
Zammad contact form

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2316]
**Is your feature request related to a problem? Please describe.**
Malte needs a new offer which allows embedding/attaching a contact form into a page.
The collected information shoul look sth. like this:
```
Zimmernummer:

Name:

[x] Ich möchte digital kontaktiert werden:
---- 8< -----
(Eins von beiden Pflicht, wenn Häkchen gesetzt. Ansonsten verschwindet die Auswahl.)

Telefonnummer:

E-Mail:
---- >8 -----

Ich möchte von einer [männlichen/weiblichen/egal] Person kontaktiert werden.

Optional Textfeld:
```

**Describe the solution you'd like**
A contact form is rendered (as an offer) for Malteser.

- [x] create an offer "hilfebutton" similar to sprungbrett
- [ ] implement the design for the "hilfebutton" form
- [x] ~~as the backend ticket is not yet merged & released hard code the form in the content and comment it out before merging~~

**Describe alternatives you've considered**
- HTML forms in content

**Additional context**
- #2315 
- https://nextcloud.tuerantuer.org/index.php/f/4782047
- https://nextcloud.tuerantuer.org/index.php/f/3906203

**Comment by sarahsporck** [comment]
@hauf-toni We can schedule an appointment, to discuss what's necessary for this.

**Comment by LeandraH** [comment]
Here are some user stories from Malteser for this: https://nextcloud.tuerantuer.org/index.php/apps/files/?dir=/Projects/Malte/50_Notizen%20und%20Themensammlungen%20f%C3%BCr%20Calls&fileid=522263

**Comment by hauf-toni** [comment]
Design-proposal can be found [📍 here ](https://www.figma.com/file/EiRpMhSqscuaChGdhNVZQ4/MALTE-App?type=design&node-id=3%3A22&mode=design&t=BFPUggPWcwUwFBC4-1)

**Comment by LeandraH** [comment]
Looks great!

**Comment by sarahsporck** [comment]
@osmers it would be nice if you could also look over the design proposal whether everything is present :)

**Comment by osmers** [comment]
@sarahsporck I'll have a look tmr :)

**Comment by osmers** [comment]
@sarahsporck I made some comments within the design - but overall I think it looks really good.
