### ISSUE TITLE
Update Android Version

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2326]
**Is your feature request related to a problem? Please describe.**
Google won't let us update our App in the Play Store after 31 August if we haven't updated to Android 13 (API 33) by then.

**Describe the solution you'd like**
Update to API 33.

**Describe alternatives you've considered**
Let's not.

**Additional context**
[Add any other context or screenshots about the feature request here.](https://play.google.com/console/developers/5269030016285360668/app/4974497225878557026/policy-center)

**Comment by sarahsporck** [comment]
see https://github.com/digitalfabrik/lunes-app/issues/955#issuecomment-1685809982
