### ISSUE TITLE
Update Android Version

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2327]
**Is your feature request related to a problem? Please describe.**
Google won't let us update our App in the Play Store after 31 August if we haven't updated to Android 13 (API 33) by then.

**Describe the solution you'd like**
Update to API 33.

**Describe alternatives you've considered**
Let's not.

**Additional context**
https://play.google.com/console/developers/5269030016285360668/app/4974497225878557026/policy-center

**Comment by sarahsporck** [comment]
This one seems to be a duplicate @LeandraH? Reopen if I'm wrong :)

**Comment by LeandraH** [comment]
Yup, sorry, I thought I'd closed it, must have forgotten 😅
