### ISSUE TITLE
Replace png icons with svgs

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2328]
Replace all png icons we are still using with the svgs created by Toni. Usages are probably all in the build-configs.

![Image](https://github.com/digitalfabrik/integreat-app/assets/18463686/fc8a234d-7448-4b4c-8f14-735a993a60c1)
![Image](https://github.com/digitalfabrik/integreat-app/assets/18463686/5ce55979-30df-4cb9-a0c7-8860591f4a5f)
![Image](https://github.com/digitalfabrik/integreat-app/assets/18463686/7676d7ea-4345-4f16-b00b-9c2baa645811)
![Image](https://github.com/digitalfabrik/integreat-app/assets/18463686/7bdd52da-1947-4969-acf4-a703b1df10a2)
![Image](https://github.com/digitalfabrik/integreat-app/assets/18463686/a4a40126-d582-4ce2-b235-9f7371740136)

**Comment by hauf-toni** [comment]
Icons (svgs) can be found [📍 here](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=2075%3A55&mode=design&t=dtxca0WmmDM8nZ0A-1)

**Comment by steffenkleinle** [comment]
Hey @hauf-toni, sorry to bother you and not think about that sooner but there is a few more icons we'd need a svg version from:
![app-icon-cornered](https://github.com/digitalfabrik/integreat-app/assets/29095487/bad631e8-19ad-4907-ba16-5aa8007e6155)
![app-logo](https://github.com/digitalfabrik/integreat-app/a
![app-logo](https://github.com/digitalfabrik/integreat-app/assets/29095487/c237d8aa-7512-4c88-bf88-576efb45ff81)
ssets/29095487/c7f6da5a-16d4-4e88-840d-740a6954e063)

**Comment by hauf-toni** [comment]
I have added the svgs for Integreat + Malte ✅ 

Unfortunately, the only version of the "Hallo Aschaffenburg" Logo I could find is very poor quality. I can rebuild the svg as close to the original as possible but a high resolution image of the original logo would really help to archieve a better result. 🔍

**Comment by steffenkleinle** [comment]
Thank you!

@FritjofK do you know if we perhaps still have a high quality version of this icon?
![app-logo](https://github.com/digitalfabrik/integreat-app/assets/29095487/c7f6da5a-16d4-4e88-840d-740a6954e063)

If not, this is not a problem I guess, then we'll just keep the current .png icon. In the end aschaffenburg is also not paying us for this optimization.
