### ISSUE TITLE
Issue template for design tickets

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2374]
**Is your feature request related to a problem? Please describe.**
As a **Designer** I want to quickly and consistently create issues in the project.

**Describe the solution you'd like**
Create an issue template for design tickets.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by steffenkleinle** [comment]
Related to https://github.com/digitalfabrik/lunes-app/issues/984

**Comment by sarahsporck** [comment]
Do we actually need separate design templates for integreat, as we decided to do everything in one ticket?
