### ISSUE TITLE
POI filter: show number of found POIs

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2379]
**Is your feature request related to a problem? Please describe.**
As a user of a POI filter, I want to see if a filter has results or not, so I can see if the tap on "Orte anzeigen" is worth it or useless.

**Describe the solution you'd like**
The number of matching pois should be displayed in the `Orte anzeigen` button:
![image](https://github.com/digitalfabrik/integreat-app/assets/29095487/e8848259-5273-4751-b119-377a8f339ab7)

If no pois are matching, the button should be displayed and the message changed:
![image](https://github.com/digitalfabrik/integreat-app/assets/29095487/17ff1e73-326c-40ff-8919-812e9cc7b931)

See the design [here ](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=1731%3A54&mode=design&t=5c6Wzwv2sdjqI6GX-1).

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by f1sh1918** [comment]
Please provide a design for the filterbar @hauf-toni

**Comment by hauf-toni** [comment]
📍 design proposal can be found [here ](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=1731%3A54&mode=design&t=5c6Wzwv2sdjqI6GX-1)

**Comment by LeandraH** [comment]
Looks good to me

**Comment by steffenkleinle** [comment]
LGTM as well, thanks! Does anybody know if we have a ticket for a design somewhere for the category search (i.e. showing the number of search results in the following screen)?
<img src="https://github.com/digitalfabrik/integreat-app/assets/29095487/e47b6942-4ee0-4d57-9d97-fd66cbcf4ce3" width="200px" />
