### ISSUE TITLE
Make the e2e tests less flaky

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2386]
**Is your feature request related to a problem? Please describe.**
The e2e tests are quite flaky which reduces our confidence in the pipeline.

**Describe the solution you'd like**
We should check which tests exactly keep failing, and what we can do to improve it. Possibilities off the top of my head:
- More retries
- Longer timeout
- Rewrite the test to look for something else

**Describe alternatives you've considered**
We could leave everything like it is because it is okay, just annoying. Or we could remove the failing tests, which I think we really really shouldn't.

**Comment by sarahsporck** [comment]
And of course also update the e2e dependencies.

**Comment by LeandraH** [comment]
Additional info: 9 out of the last 9 failed e2e tests were because of `change language should open language selector: Error: expect(received).toBeTruthy() Received: false`.
