### ISSUE TITLE
Better color for go back arrow in location mobile

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2396]
**Is your feature request related to a problem? Please describe.**
The current color of the back arrow in the location screen for mobile looks weird (top right of the map). Also it has a bad contrast.

**Screenshots**

***Current state***
<img width="500" alt="Bildschirmfoto 2023-08-28 um 16 56 25" src="https://github.com/digitalfabrik/integreat-app/assets/28013368/3ee3bf14-bd75-40e6-822e-fb89ef90985a">
***Proposal (invert the border and filling color)***
<img width="500" alt="Bildschirmfoto 2023-08-28 um 16 56 13" src="https://github.com/digitalfabrik/integreat-app/assets/28013368/24d3f9a8-7518-4b5d-9b5b-c263eddd478a">

**Comment by hauf-toni** [comment]
your suggestion makes a lot of sense, the contrast is much better when the colours are inverted. this can be implemented like this 👍🏻
