### ISSUE TITLE
Upgrade Firebase

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2403]
**Is your feature request related to a problem? Please describe.**
Firebase has now already moved onto version 18+, while we are stuck on 14 rn. The reason for that is that all firebase versions 15+ require `use_frameworks` on ios. However `use_frameworks` is not compatible with `flipper` which would mean we have to decide flipper vs firebase. 
There is also the option to dynamically (during runtime) link [firebase on ios](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks), however this is not really recommended.
Discuss in the team what option fits us best. [Version 14 also still seems to be maintained](https://www.npmjs.com/package/@react-native-firebase/app?activeTab=versions) in the project, as this does not only affect us. 

**Describe the solution you'd like**
- First discuss in the team whether we want to update, then take further action.

**Comment by f1sh1918** [comment]
Since we decided that we want to keep flipper for ios, we not gonna update firebase for now
