### ISSUE TITLE
Make cursor a pointer on hovering over footer links

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2405]
**Is your feature request related to a problem? Please describe.**
In the web app, the links in the footer should announce that they are interactive by making the cursor a pointer when it hovers over a link.

**Additional context**

![Image](https://github.com/digitalfabrik/integreat-app/assets/18513943/ef3f34ed-4e84-4830-b877-0a84176f4be5)

**Comment by steffenkleinle** [comment]
I can't reproduce this, for me the cursor is correctly a pointer.
