### ISSUE TITLE
Category labels not readable in location category filter

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-app#2424]
### Describe the Bug
When you filter for location categories the labels of the category are truncated. That may lead to not know what the category means that you want to filter for

### Steps to Reproduce

1. [Go to '...'](https://netzwerkobdachwohnen.de/augsburg/de/locations)
2. Orte filtern
3. Check the filter button labels

### Expected Behavior

The category labels are readable

### Actual Behavior
The category labels are not readable if they exceed one line

### Additional Information
The buttons should take 100x100 and the labels should not have ellipsis but word-break: break-word

Current:
<img width="310" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/37902063/cc4ff644-ebc2-4fe9-a85f-d6b1758a5b68">

Proposal
<img width="494" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/37902063/b330b409-2c8a-4fdd-8f57-38b22513ecb6">

**Comment by steffenkleinle** [comment]
Done in #2425.
