### ISSUE TITLE
Settings icon in header too close to the edge

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2430]
### Describe the Bug

The settings icon is too close to the edge of the screen now, it seems to have lost some padding.

### Steps to Reproduce

1. Open the app in iOS or Android
2. Look at the header

### Expected Behavior

I'd like the icon to not look squashed against the edge.

### Actual Behavior

It looks a little hard to actually tap on the icon because it is so far right.

### Additional Information

<img width="211" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/18513943/6272ce42-a97c-4fe5-bfa8-de6addb393ee">

**Comment by anxbt** [comment]
### **Cant run it locally** 
 tried the following commands 
-installed `yarn`
-ran `yarn start
yarn android`

i even made changes in the  **package.json** file

`"scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "lint": "yarn run eslint",
    // ... other scripts
  },`

**Comment by SteffiStuffel** [comment]
@anxbt Have a look at our readmes: 
[General Readme](https://github.com/digitalfabrik/integreat-app)
[Setup for native](https://github.com/digitalfabrik/integreat-app/blob/main/native/README.md)

You first need to `yarn install` and then change no folder `native` and run `yarn start` and `yarn android`. You need to have set up an Android Emulator before.

**Comment by anxbt** [comment]
I know this issue is closed could u help me to run this Integrat app for Android locally. I have a Android emulator installed already as I   work with React native.i ran "yarn" then "yarn start" then "yarn Android". I even copied the whole original package.json file .

@lunars97 could u please help me.

**Comment by lunars97** [comment]
@anxbt Hi, sure. In order to run android emulator, you need to change to native directory and there you need to run `yarn start` and `npx react-native run-android`
