### ISSUE TITLE
Deep linking is broken, when other city is open

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2440]
### Describe the Bug

When opening one city, e.g. Augsburg and then opening a deep link in another city, e.g. Testumgebung, the app is broken. See the attached video. This only happens if no browser is installed on the phone. This also happens for clicking on external links or links to different cities or languages.

### Steps to Reproduce

1. Install Integreat and open city of augsburg
2. open a deeplink e.g. `npx uri-scheme open https://integreat.app/testumgebung/de/locations --android`
3. See error

### Expected Behavior

Deep link should be opened correctly in the in app browser

### Actual Behavior

App is stuck in some sort of loop i guess. Reloading all the time

### Additional Information

https://github.com/digitalfabrik/integreat-app/assets/18463686/e8dc32aa-7f4a-426d-bc88-e42ea1e85013

**Comment by LeandraH** [comment]
I can't reproduce this on an emulated Pixel 7 with API 34. Can you check if it works on a real device?

**Comment by SteffiStuffel** [comment]
I have the same bug as reported above on a real device: Galaxy A22 Android 13

**Comment by steffenkleinle** [comment]
I can't reproduce this on a real device (Xiaomi Redmi Note 10 Pro). For me just the InAppBrowser opens the internal link.

**Comment by ztefanie** [comment]
I can reproduce this on a real device. (Samsung Galaxy A22 - Android 13). Checked out HomeScreen of Region of Amberg (live cms). Executed `npx uri-scheme open https://integreat.app/testumgebung/de/ --android`. Error as in the video above occurs. Cleared data tried again with test-cms (same regions and screen), same error.

**Comment by ztefanie** [comment]
Both for Integreat productive (2023.10.3) and current main.
