### ISSUE TITLE
Translate app constants

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2445]
**Is your feature request related to a problem? Please describe.**
Since the last time we translated our app constants some time has passed and a lot of new constants were added. We should therefore translate the constants again.

**Describe the solution you'd like**
The constants should be exported, converted to odt and sent to @osmers. When we get them back translated, import them again.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

### Describe the Bug

When I open the feedback modal in languages other than German, most of the text is in German only

### Steps to Reproduce

1. Go to 'https://integreat.app/lkansbach/en'
2. Click on 'Feedback'
3. See that the feedback modal is largely in German

### Expected Behavior

It should be all in the selected language.

### Actual Behavior

It is mostly in German.

### Additional Information

<img width="415" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/18513943/d2412b42-e46f-439f-99e6-08e2c28e01be">

**Comment by steffenkleinle** [comment]
Thats not a bug, we just need to do the translations again. Would probably still make sense to do this :)
