### ISSUE TITLE
Fix Google Api Error

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2448]
### Describe the Bug

Google Api Error: Unauthorized - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

### Steps to Reproduce

See here: https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/9478/workflows/e9968338-fb89-465c-9904-60af46c8a4bd/jobs/53656

**Comment by LeandraH** [comment]
I think the `GOOGLE_SERVICE_ACCOUNT_JSON` might have expired (https://github.com/digitalfabrik/integreat-app/blob/main/docs/cicd.md#android-variables) but I can't find it in the Google Play Console and suspect that I don't have access to that. Maybe someone else can check?

**Comment by steffenkleinle** [comment]
I think I don't have access either, maybe ask in mattermost :)

**Comment by svenseeberg** [comment]
This is used for Firebase, right?

**Comment by steffenkleinle** [comment]
I actually don't thin that an expired json is the problem. In the first delivery run on monday, deliver_integreat_android AND deliver_aschaffenburg_android failed, upon restarting ONLY deliver_integreat_android failed while deliver_aschaffenburg_android failed :/

**Comment by steffenkleinle** [comment]
This is apparently a problem on googles side and was fixed by fastlane with release 2.215.1, see https://github.com/fastlane/fastlane/issues/21507#issuecomment-172311682.
