### ISSUE TITLE
Add "Only by appointment" to the opening hours of POIs

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2457]
**Is your feature request related to a problem? Please describe.**
As described in https://github.com/digitalfabrik/integreat-cms/issues/2398, there are POIs that are only "open" if you have an appointment. The CMS ticket for it is almost done, we should figure out how to handle this in the app.

**Describe the solution you'd like**
As a user of the Integreat App I want to see on which days I need an appointment to go to a POI so that I do not waste my time and have all the relevant information before going.

**Describe alternatives you've considered**
We could ignore it, which seems like a terrible idea since it will soon be possible to add the information in the CMS.

**Additional information**
This draft PR might be a good point to start or take code from:
https://github.com/digitalfabrik/integreat-app/pull/2722

**Comment by LeandraH** [comment]
@hauf-toni Sorry, here is the issue I meant.

**Comment by hauf-toni** [comment]
Design proposal can be found 🚩 [here](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=1842%3A385&mode=design&t=4RoNJHeGcYYyI8z4-1)

**Comment by LeandraH** [comment]
Looks good though if I understand the CMS ticket correctly, the "open by appointment"-label applies to specific days and not everything. Sorry, I didn't realize that until now. But I guess we can simply move the text "Termin erforderlich, [...]" to under the days where you need an appointment?

**Comment by hauf-toni** [comment]
> Looks good though if I understand the CMS ticket correctly, the "open by appointment"-label applies to specific days and not everything. Sorry, I didn't realize that until now. But I guess we can simply move the text "Termin erforderlich, [...]" to under the days where you need an appointment?

An alternative design proposal can be found on figma as well

**Comment by LeandraH** [comment]
Looks good to me, I think we can start working on that :)

**Comment by ztefanie** [comment]
Blocked by https://github.com/digitalfabrik/integreat-cms/issues/2398

**Comment by timobrembeck** [comment]
The corresponding CMS issue is now fixed, the opening hours contain an additional boolean field `appointmentOnly` now.
