### ISSUE TITLE
Github Sentry Integration

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2460]
**Is your feature request related to a problem? Please describe.**
Issues that are relevant (find a good metric and filters) should be automatically be created in github

**Describe alternatives you've considered**
If this is not suitable / too expensive or whatever as a fallback we want a reminder in mattermost to look at sentry.

**Comment by f1sh1918** [comment]
i created a Sentry github app for this (digitalfabrikMember)
Now these GHApp Config has to be added to our on premise server for sentry

**Comment by sarahsporck** [comment]
So this is blocked until the infra ticket is done? Could you move it back into the backlog then? :)

**Comment by sarahsporck** [comment]
Is this closed @f1sh1918
