### ISSUE TITLE
Push notifications won't be received without latest update

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2464]
### Describe the Bug

On the community event on thursday Stadt Regensburg mentioned that they do not receive push notifications without having the latest update installed on Android. They described that they had the situation several times that they were wondering why they haven't received the push notifcation and then found out they hadn't installed the latest version of the app. After the update the push notifications where received again (but of course former sent push notifications are not post-delivered).

They asked if we could investigate that case because they had the feeling that other apps are downwards-compatible for push-notifications for some versions. Do we only support the latest version of the app to receive push-notifications? maybe that's also a setting. in firebase

### Steps to Reproduce

Use an older version of integreat-app (>1 month, <6 month).

### Expected Behavior

Push Notifactions should be also received on older versions of the app (> 1 month, <6 month)

### Actual Behavior

push notifications are not received.

### Additional Information

Stadt Regensburg can be contacted for more information: aim@regensburg.de - name of the contact person can be asked internally.

**Comment by steffenkleinle** [comment]
We will ship a fix on Monday which fixes PNs on Android 13 (#2451). Maybe that was the problem here as well?

**Comment by ztefanie** [comment]
@dkehne Can you please check if this is fixed by the release?

**Comment by steffenkleinle** [comment]
Closing this as apparently this does not happen anymore.
