### ISSUE TITLE
unknown error at Testumgebung

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2474]
### Describe the Bug
Only in location "Testumgebung" selecting Imprint results in unknown error. (Only Malte app)

### Steps to Reproduce

1. select Testumgebung 
2. Click on Imprint
3. See error

**Comment by LeandraH** [comment]
Sadly not a duplicate of https://github.com/digitalfabrik/integreat-app/issues/2462

**Comment by steffenkleinle** [comment]
This error just happened because there was no disclaimer set in the cms. Closing.
