### ISSUE TITLE
Footer link "about integreat" leads to chrome safety warning

### ISSUE THREAD

**Issue by relentless95** [digitalfabrik/integreat-app#2475]
### Describe the Bug

In the footer of the web app. If i click on about integreat, i get a warning from google chrome. 

### Steps to Reproduce

1. Go to https://integreat.app/testumgebung/en/disclaimer in google chrome.
2. Scroll down to the bottom. 
3. Click on about integreat

### Expected Behavior

No error

### Actual Behavior

Chrome warning

### Additional Information

![Image](https://github.com/digitalfabrik/integreat-app/assets/76557555/24843b61-359b-481e-a85c-1119bfd76a73)

**Comment by LeandraH** [comment]
I haven't been able to reproduce it so far, tried Chrome, Firefox, Opera and Safari. But I am also on a Mac and Marc is on a Windows machine.

**Comment by Docmale** [comment]
I can not reproduce this in chrome (Version 117.0.5938.92 (Offizieller Build) (64-Bit)) on Win11, but saw this sometimes in the past. Don't remember what link.

**Comment by Docmale** [comment]
Correction: Can't reproduce with Integreat 23.9.5 but with Integreat 23.9.6 I get the same warning.

**Comment by sarahsporck** [comment]
Similar issue and porbably fix (?) https://github.com/getsentry/sentry/issues/44820

**Comment by sarahsporck** [comment]
"Blocked" by https://openproject.tuerantuer.org/projects/infra/work_packages/2599/activity

**Comment by svenseeberg** [comment]
Fixed: https://integreat.app/.well-known/assetlinks.json & https://integreat-app.de/.well-known/assetlinks.json

**Comment by svenseeberg** [comment]
See https://chat.tuerantuer.org/digitalfabrik/threads/9jf9qx1a6pbipbctszfxdc3guc

**Comment by LeandraH** [comment]
I can't see that link, can you elaborate here?
