### ISSUE TITLE
Wrong app name in Feedback

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2477]
### Describe the Bug

Wrong app name on page Feedback "... da es uns hilft **Integreat** zu verbessern." in Malte app and Hallo Aschaffenburg app 

### Expected Behavior

The text should sound somewhat like "... da es uns hilft Malte zu verbessern." "... da es uns hilft Hallo Aschaffenburg zu verbessern."

**Comment by sarahsporck** [comment]
I overlooked that this is a `good first issue` ^^. Maybe sth for @relentless95?

**Comment by relentless95** [comment]
yes, please give me some more.

**Comment by sarahsporck** [comment]
Then feel free to work on this. If you have any questions, send me a message 👍🏼
