### ISSUE TITLE
Add translation for "Link kopieren"

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2481]
### Describe the Bug

The toolar-button "Link kopieren" does not have a translation.

### Steps to Reproduce

1. Go to https://integreat.app/neuss/tr
2. Look at the toolbar

### Expected Behavior

Translation should be there

### Actual Behavior

German everywhere

**Comment by ztefanie** [comment]
Duplicate of [#2245 ](https://github.com/digitalfabrik/integreat-app/issues/2445)
