### ISSUE TITLE
Site 'Sprungbrett' could not be found

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2490]
### Describe the Bug

Inside 'Offers' the link to 'Sprungbrett' leads to "Sorry, but the requested page could not be found"

### Steps to Reproduce

1. In 'Testumgebung' or  'Augsburg (Stadt)' open 'Offers'
2. klick 'Sprungbrett' 

![Bild1](https://github.com/digitalfabrik/integreat-app/assets/21236324/c2d7a2fc-997b-4a04-829e-d76f437e5c6e)

**Comment by LeandraH** [comment]
@svenseeberg That looks familiar. I am again getting a 301 and then a CORS missing allow origin.

**Comment by svenseeberg** [comment]
If you access https://integreat.app/proxy/sprungbrett/app-search-internships?location=86150 instead of https://web.integreat.app/proxy/sprungbrett/app-search-internships?location=86150 then there would be no 301. But the page itself seems broken.

**Comment by sarahsporck** [comment]
This is fixed now. Wasn't anything we are responsible for.
