### ISSUE TITLE
Minimize main thread work

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2498]
**Is your feature request related to a problem? Please describe.**
Google still thinks our mobile performance is too slow, i.e. we have a LCP longer than 2.5 on most sites on mobile. Therefore we should try to speed up our web app more.

**Describe the solution you'd like**
Investigate whether we can minimize main thread work: https://developer.chrome.com/docs/lighthouse/performance/mainthread-work-breakdown/?utm_source=lighthouse&utm_medium=lr#how-to-minimize-main-thread-work

**Describe alternatives you've considered**
None.

**Additional context**
LCP:
https://search.google.com/search-console/core-web-vitals/drilldown?resource_id=https%3A%2F%2Fintegreat.app%2F&item_key=CAMQAhgC

Part of #2371 
relates to: #2499

**Comment by ztefanie** [comment]
"When I look at the performance tab I can see that the main bundle is taking around 5s to be fully loaded. As we are using HTTP/2 in production, splitting the bundle into smaller chunks can result in better performance. Check out the AggressiveSplittingPlugin. There are several guides on how to implement this: e.g. splitting react and react-dom into separate chunks or just by setting the chunk max size. I think this block article is a good starting point what can be achived here -> https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-2-page-load-performance-33b932d97cf2"
