### ISSUE TITLE
Clicking on a cluster on the map should zoom in on it

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2504]
**Is your feature request related to a problem? Please describe.**
When I'm on the map and click on a cluster, I expect to zoom in on that. As an example, if I go on http://localhost:9000/testumgebung/de/locations/ in a laptop browser, I see a cluster of three locations in Berlin. When I click on that "3", nothing happens. It should instead center that spot and zoom in. Same goes for native.

We currently have that behavior when the user double clicks on a cluster but other apps usually zoom in from a single click / tap, if it is on a cluster.

**Describe the solution you'd like**
I want the map to center on the cluster and zoom in (at least a little, doesn't have to be enough to open up the cluster).

**Describe alternatives you've considered**
We could leave it like it is but it's not what other maps do, so users probably expect a zoom.

**Comment by nikhilgarg26** [comment]
hey @LeandraH can i work on this issue, could please assign this to me ?

**Comment by LeandraH** [comment]
That's awesome, thank you!

**Comment by LeandraH** [comment]
Hey @nikhilgarg26, how's it going with this? Do you have any questions that we can maybe help you with?

**Comment by LeandraH** [comment]
Hey @nikhilgarg26, are you still working on this? If not, I'd remove you as the assignee so that someone else can have a go but thanks for having a go at it!
