### ISSUE TITLE
Rename api-client

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2513]
**Is your feature request related to a problem? Please describe.**
As our api-client has grown and handling a lot more stuff, than only the api, the name is no longer matching. Renaming it would make sense. Discuss a new name with the team before working on this.

**Describe the solution you'd like**
Rename the api-client everywhere.

**Describe alternatives you've considered**
Keep it as it is.

Decision from the grooming: rename `api-client` to `shared` and create a subfolder `api`. Move files to the correct directories. Create index.ts file so importing is easier.

**Comment by sarahsporck** [comment]
Hmm. I'd propose to go another step and keep the `api-client` for backend communication, but introduce another project `shared` or sth. like that.

**Comment by steffenkleinle** [comment]
How about just using `shared` but having a sub-folder `api` or similar?

**Comment by sarahsporck** [comment]
I guess that would also be fine, though, personally I prefer smaller packages/modules.
