### ISSUE TITLE
Broken tünews link

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2529]
### Describe the Bug

Tapping on "tünews" under news results in error page "Die Anfrage konnte nicht bearbeitet werden"
in Integreat and Malte

### Steps to Reproduce

1. Go to news in location Augsburg (Stadt) or Malte: Berlin (UA TXL)
2. Click on tünews

**Comment by LeandraH** [comment]
Also in web: https://integreat.app/augsburg/de/news/tu-news

**Comment by LeandraH** [comment]
@svenseeberg Getting an error 500 from https://tunews.integreat-app.de/v1/news/languages

**Comment by ztefanie** [comment]
Seems not to be an app issue

**Comment by LeandraH** [comment]
Works again!
