### ISSUE TITLE
Search not found layout annotations

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2531]
Concerning #2472 
Search not found feedback: 2 annotations:
- Web: ~Headline "Kommentar" is far away from the input field, this is somewhat confusing and may lead to misinterpretation. I would like to have the headline as near as for the email field and the explaining text above.~ See #2565 
- Native: On smaller displays the "Abschicken" button is not visible because of the gap between email-field and button,  just remove the gap.

**Comment by steffenkleinle** [comment]
Will be done in #2597.
