### ISSUE TITLE
The poi panel scrollable horizontally

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2543]
### Describe the Bug

The poi panel shouldn't be scrollable horizontally. At the moment this is possible and the panel is scrollable.

### Steps to Reproduce

1. Go to https://webnext.integreat.app/muenchen/de/locations (with desktop screen width)
2. Try to scroll horizontally in the panel on the left side
4. It is scrollable (see screenshot)

### Expected Behavior

The poi panel should not scroll horizontally.

### Actual Behavior

The poi panel does scroll horizontally.

### Additional Information

![image](https://github.com/digitalfabrik/integreat-app/assets/29095487/78ef00be-8d5d-42d2-afee-5b854e4ab448)

**Comment by khoadangtran** [comment]
Hey, I want to work on this issue, Can you please assign it to me?

**Comment by steffenkleinle** [comment]
> Hey, I want to work on this issue, Can you please assign it to me?

Hey @khoadangtran, sadly @lunars97 is already working on the issue but we really appreciate it, thanks! Would any of the issues here fit you as well? https://github.com/orgs/digitalfabrik/projects/2/views/5
