### ISSUE TITLE
Can not send feedback after opening the keyboard 

### ISSUE THREAD

**Issue by clarabracklo** [digitalfabrik/integreat-app#2547]
I am using the native app on an iPhone (15.6.1). When opening the feedback funktion at the top right and start typing feedback I can not close the keyboard anymore and therefore can not send any feedback. 

~~I also received the feedback from Munich that no feedback has been send since changing the functionality. Might be connected could also be because the functionality is not visible on every page footer anymore (harder to find).~~ Handled in #2548

**Comment by ztefanie** [comment]
@LeandraH have you tested on Android or why have you added the android label?

**Comment by LeandraH** [comment]
Nope, sorry, must have mistyped or something

**Comment by f1sh1918** [comment]
@clarabracklo 
you should be able to close the keyboard by clicking on the screen above the keyboard?
Since this is a Textarea and not a Textfield you are able to create multiple lines by clicking "Enter" Button.
You can either use the "Enter" Button for new line or leaving the TextField
I think the main issue is not closing the keyboard but to find the functionality in the overflow menu

**Comment by steffenkleinle** [comment]
> @clarabracklo you should be able to close the keyboard by clicking on the screen above the keyboard? Since this is a Textarea and not a Textfield you are able to create multiple lines by clicking "Enter" Button. You can either use the "Enter" Button for new line or leaving the TextField

 Not easily being able to close the feedback was also already reported in the A11y report, so perhaps we should reassign `enter` to close the feedback? Does being able to add linebreaks to the feedback comment add any benefits?

>I think the main issue is not closing the keyboard but to find the functionality in the overflow menu

I think these are just two different issues and therefore should have two different tickets.

**Comment by f1sh1918** [comment]
yes you are right i also thought about that. Gonna test how the `TextArea` behaves if you don't break by enter

**Comment by f1sh1918** [comment]
okay i think as Steffen described the best option is to switch the "Enter" Button by "Done" button and close the keyboard. The user can not break lines manually but it will happen automatically.
i will also add a keyboard aware scroll view so the text remains visible during typing

**Comment by clarabracklo** [comment]
Thank you very much! This feedback has come up during our community workshops and if there are any changes implemented I think it would be great to communicate that in our facebook group so that our users feel heard . Do you think you could possibly ping Leonie when you are done @f1sh1918 ?
