### ISSUE TITLE
Test `CategoriesToolbar.tsx`

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2569]
**Is your feature request related to a problem? Please describe.**
We currently don't have any good starter tickets for web left. Therefore, to allow newcomers to get to know the project and get familiar with react, we can use tests for that. The CategoriesToolbar is not covered in our code base entirely. 

**Describe the solution you'd like**
- add a test file `CategoriesToolbar.spec.tsx` in the `web/src/components/__tests__/` directory
- write a test that checks whether the correct pdf url is used in the case
    - a) the category is a root category (it is visible in the dashbord page)
    - b) the category is not a root category
- consider the remaining code as a black box which you don't know about

Use the other tests as helper to reuse existing patterns and get to know [@testing-library/react](https://testing-library.com/docs/react-testing-library/api). Also checkout [jest](https://jestjs.io/), to get to know the test framework.

**Comment by Njivaniaina2407** [comment]
@sarahsporck  I just commited `CategoriesToolbar.spec.tsx` file. Is it necessary to make a pull request for this?

**Comment by sarahsporck** [comment]
Jep. We always make pull requests for all changes :)
