### ISSUE TITLE
Feature Request: Add parameters for filter selection when calling the POI map

### ISSUE THREAD

**Issue by nassabay** [digitalfabrik/integreat-app#2571]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to include a selection via filtering when calling the map, so when the user follows this link to the map, the map already shows the selected filter.

**Describe the solution you'd like**
Add the possibility to include the filter parameters when calling the POI map. These filter parameters should be selected already and define the view.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by steffenkleinle** [comment]
We'd need additional query parameters:
- Selected poi category
- Only show currently open (optional)
- Filter selection currently opened (optional)

We should probably also think about error handling (e.g. if poi specified by slug is not part of the selected filter...).
