### ISSUE TITLE
Use warning color for notes

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2577]
**Is your feature request related to a problem? Please describe.**
As a user I want to be able to identify warnings/notes as such. Using the theme color as a color for warnings/notes might not be suitable for that.

**Describe the solution you'd like**
- introduce a new warning color (yellow) and replace existing warning color (Feedback Modal)

Both colors should go to colors.ts in build configs common.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by IsabellaTG** [comment]
@steffenkleinle To get a better understanding of the issue: Where I can find the notes in web and app? Or do you have an
example of the current warning categories and the used colors?

**Comment by steffenkleinle** [comment]
> @steffenkleinle To get a better understanding of the issue: Where I can find the notes in web and app? Or do you have an example of the current warning categories and the used colors?

Atm its only used in the feedback, see the screenshot:

<img src="https://github.com/digitalfabrik/integreat-app/assets/29095487/211f90b9-2eda-4d8e-9834-80de489da20a" width="500px" />

**Comment by f1sh1918** [comment]
@hauf-toni 
can you please provide hex colors for yellow and red. Not sure if they already exist in figma?

**Comment by hauf-toni** [comment]
My recommendation would be to use one of these options:
<img width="732" alt="alert color integreat" src="https://github.com/user-attachments/assets/17059506-b3aa-4fbc-a37a-8212a4880463">
I prefer the orange (#FFA726) over the muted yellow (#F1C100) as it offers more distinguishing features, especially for visually impaired users. Both options are conceivable.
