### ISSUE TITLE
Missing translation "searchTermDescription"

### ISSUE THREAD

**Issue by Njivaniaina2407** [digitalfabrik/integreat-app#2581]
### Describe the Bug

Translation is missing 

### Steps to Reproduce

1. Go to 'http://localhost:9000/testumgebung/de/search/?query=gcbcg'
2. Check Label "searchTermDescription"

### Expected Behavior
Translation Text should be displayed

![image](https://github.com/digitalfabrik/integreat-app/assets/150787419/427807c6-2a3f-4a44-9098-dd338d949737)

### Actual Behavior
Translation Text is not displayed

### Additional Information

<details>
  <summary>Traceback</summary>

```

```

</details>

**Comment by sarahsporck** [comment]
Did you see that on your branch? Did you change the description accidentally? On main this is working

**Comment by steffenkleinle** [comment]
On webnext I can reproduce it (https://webnext.integreat.app/testumgebung/de/search/?query=jjj), not on beta or production though. I guess it got lost during a merge.
