### ISSUE TITLE
Add purpose string translations for calendar permission

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-app#2608]
**Is your feature request related to a problem? Please describe.**
Currently we only have the camera permission purpose strings in the Info.plist in english.
We want them to be available in other languages

**Describe the solution you'd like**
Translate these purpose strings in the particular languages and add them. `(ios/Integreat/<lang>.lproj)`
Please keep these english version in the `Info.plist` because apple checks only this file for purpose strings when uploading a new app version.

**Additional context**
```js
	<key>NSCalendarsUsageDescription</key>
	<string>Integreat wants to access the calendar to add an event.</string>
	<key>NSCalendarsFullAccessUsageDescription</key>
	<string>Integreat wants to access the calendar to add an event.</string>
```

**Comment by sarahsporck** [comment]
Ask @osmers for translations.

**Comment by steffenkleinle** [comment]
Still missing:
- [x] Use Sie for malte help form
- [x] Submit for translations
- [ ] Add translations
- [ ] Add purpose strings for calendar permissions to `ios/Integreat/<lang>.lproj` files
