### ISSUE TITLE
Translations are marked as available but no content Web-App

### ISSUE THREAD

**Issue by clarabracklo** [digitalfabrik/integreat-app#2617]
I am not sure if this is an app or cms issue, maybe you have to move it. 

I have just visited https://integreat.app/bodenseekreis/de/ukraine-flucht/erste-informationen/hilfe-und-solidaritaet-im-landkreis-bodenseekreis in my browser (Firefox). 
When I am on the German page and hover over the translation options a lot of them are black (seem to be available). However, when I click on them (for example English) no translation is available and I can not get back to the German page. Some translations are available (e.g. Romanian). Can you reproduce this problem and is it known already? 

![grafik](https://github.com/digitalfabrik/integreat-app/assets/26277354/c113e12d-22f3-4964-a039-9591b66c6f7c)
![grafik](https://github.com/digitalfabrik/integreat-app/assets/26277354/d354996e-127e-41ba-bc0e-8c6e5c3ee7d1)

**Comment by steffenkleinle** [comment]
I think its a CMS issue, in available languages it says `/bodenseekreis/en/ukraine-flucht/erste-informationen/info-hotline-and-contacts/` but trying to call the API endpoints for that path results in a 404.

**Comment by ztefanie** [comment]
Yes, i also checked, this is a cms-issue. Will move it.
