### ISSUE TITLE
hallo aschaffenburg | new app store pictures for Google Play and Apple App Store

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/integreat-app#2624]
**Is your feature request related to a problem? Please describe.**
The _hallo aschaffenburg_ team has sent us new app store pictures to replace the current ones to reflect the current state of the content. 

**Describe the solution you'd like**
Replace the old store pictures as I believe they are part of the automatic release pipeline. 

**Additional context**
I have attached the files with the new pictures. 
If there are any questions (or the pictures do not fit the app store requirements) please let me know. 
If possible please try to have a release with the new pictures in January 2024 :) Thank you :) 
[Screenshots Android Phone.zip](https://github.com/digitalfabrik/integreat-app/files/13752729/Screenshots.Android.Phone.zip)
[Screenshots Android Tablet.zip](https://github.com/digitalfabrik/integreat-app/files/13752730/Screenshots.Android.Tablet.zip)
[Screenshots iOS Phone 1242x2208.zip](https://github.com/digitalfabrik/integreat-app/files/13752731/Screenshots.iOS.Phone.1242x2208.zip)
[Screenshots iOS Phone 1242x2688.zip](https://github.com/digitalfabrik/integreat-app/files/13752732/Screenshots.iOS.Phone.1242x2688.zip)
[Screenshots iOS Tablet.zip](https://github.com/digitalfabrik/integreat-app/files/13752733/Screenshots.iOS.Tablet.zip)

**Comment by steffenkleinle** [comment]
Thanks for your issue. Actually, the screenshots are not part of the pipeline for aschaffenburg so they can just be changed in the play console/app store connect. Sadly, apparently all of the screenshots have wrong sizes/aspect ratios. Do you think we should adjust them ourselves or you want to request fixed screenshots from aschaffenburg?

**Comment by FritjofK** [comment]
@steffenkleinle 
Thank you for your response. Let me take over. I will ask Aschaffenburg to change those screenshots which do no fit and then chenge them in both stores :)
