### ISSUE TITLE
Link not clickable in push notification

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-app#2626]
### Describe the Bug

A link is not always fully linked within the push notification 

### Steps to Reproduce

1. Go to https://integreat.app/castrop-rauxel/ru/news/local/5917
2. Click on the link
3. See link not opening/error

### Expected Behavior

The link should the considering the complete URL and link it entirely 

### Actual Behavior

Only part of the URL is highlighted and linked. Link does not work. 

### Additional Information

Page to edit the push notification: https://admin.integreat-app.de/castrop-rauxel/push-notifications/de/979/edit/ 

More info from Sven: https://chat.tuerantuer.org/digitalfabrik/pl/fffs5x8uxpb67gnbzc74jza6cc

**Comment by LeandraH** [comment]
The link in question is https://integreat.app/castrop-rauxel/ru/информация-помощь-украине/разрешение-на-временное-го-года, we should check on the encoding here.
