### ISSUE TITLE
Don't show last update for empty category with embedded offers

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2634]
### Describe the Bug

Showing a last update for an empty category with only embedded offers is pretty confusing, because the list of the offers was not updated last time on that dates.

Furthermore, the embedded offers should have more padding after the timestamp (see https://chat.tuerantuer.org/digitalfabrik/pl/7czoxkzkebfpxmt83qjfioa4cr).

### Steps to Reproduce

1. Go to https://webnext.integreat.app/testumgebung/de/arbeit/sprungbrett
2. See last update

### Expected Behavior

- [ ] No last update is shown if the category is empty.
- [ ] If there is content, make it obvious that the "last update" only refers to the content, e.g. by adding some padding.

### Actual Behavior

A last update is shown if the category is empty.

### Additional Information

![image](https://github.com/digitalfabrik/integreat-app/assets/29095487/3e33449f-88e1-450a-8604-76a7e7671664)

**Comment by ztefanie** [comment]
Tested on Chrome works nice :tada:

**Comment by steffenkleinle** [comment]
Native is still missing
