### ISSUE TITLE
Add tests for embedded offers/malte help offer

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2642]
**Is your feature request related to a problem? Please describe.**
We are making an effort to increase our test coverage and stability, therefore we want to enforce a good practice and always write tests, when implementing a new feature ❤️ .
Due to time pressure we weren't really able to add tests for these components. Let's add them once we are finished.

**Describe the solution you'd like**
Add tests for 
- [ ] embedded offers
- [ ] malte help offer

**Describe alternatives you've considered**
Don't add tests.

**Additional context**
https://codeclimate.com/github/digitalfabrik/integreat-app/code?q=embedded
https://codeclimate.com/github/digitalfabrik/integreat-app/code?q=MalteHelp

**Comment by steffenkleinle** [comment]
@LeandraH just a short heads up: A lot of offers stuff is removed (and a little refactored) in #2467. So perhaps it makes sense to wait with this for a little while still.
