### ISSUE TITLE
CSS Units: Px or Rem?

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2643]
**Is your feature request related to a problem? Please describe.**
We mostly use px as our units in our styling but in a few places, we use rem instead. We should decide which one we want to use (px tends to be easier for the developer, rem tends to be nicer for users who change the zoom but might not be supported by react-native), and then implement that.

**Describe the solution you'd like**
Only one kind of unit in our CSS.

**Comment by steffenkleinle** [comment]
Also related to the design system from #2414. I think we should probably do that together instead of first transitioning everything to rem/px and then adjusting it again to some other values.

**Comment by ztefanie** [comment]
I think it makes sense to have both.
px should be used for everything that should not scale with font or device size, e.g. a padding of a button
rem should be used for everything that should scale, e.g. the height of the header (if it would be set manually)

**Comment by LeandraH** [comment]
Decision for UX/UI
