### ISSUE TITLE
Under iOS the on-screen keyboard slides over the form

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2646]
### Describe the Bug

Under iOS the on-screen keyboard slides over the Malteser help form so that I can't see what I'm typing. On Android the form moves up as expected

### Steps to Reproduce

1. Go to Malte - Testumgebung - Deutsch
2. Click on [Krieg in der Ukraine] - [Hilfe für Ukrainer und Ukrainerinnen]
3. Scroll down to Help form
4. try to write into fields

### Expected Behavior

The form should move up as in Android

### Actual Behavior

on-screen keyboard slides over the Malteser help form

**Comment by f1sh1918** [comment]
Still does not work for all input fields @LeandraH 
with an additional `<KeyboardAwareScrollView extraScrollHeight={120}>` it works

https://github.com/digitalfabrik/integreat-app/assets/37902063/99ac995e-aafb-4ddd-b159-b7ddcb0c66a1
