### ISSUE TITLE
hallo aschaffenburg | new app store pictures for Apple App Store 

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/integreat-app#2649]
**Is your feature request related to a problem? Please describe.**
The hallo aschaffenburg team has sent us new and I believe now correctly sized Apple app store pictures to replace the current ones to reflect the current state of the content. 
I have already changed the Google Play Store Pictures manually. 

**Describe the solution you'd like**
Replace the old store pictures as in the Apple App Store one cannot simply switch the pictures, a new release needs be done. 
Prior discussion in Mattermost: https://chat.tuerantuer.org/digitalfabrik/pl/b4a6ewar5j8fbno8p9owkwfmxo 

**Additional context**
I have attached the files with the new pictures. 

[Screenshots für Appstores hallo aschaffenburg.zip](https://github.com/digitalfabrik/integreat-app/files/14053701/Screenshots.fur.Appstores.hallo.aschaffenburg.zip)

**Comment by sarahsporck** [comment]
The release with the new images must be created manually in App Store Connect on iOS

**Comment by FritjofK** [comment]
Thank you so much! 👍 Looks great
