### ISSUE TITLE
Make PWA install more visible

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2654]
**Is your feature request related to a problem? Please describe.**
When looking for the number of installs of the integreat app recently, I found that there are a lot of Desktop Installs for the IG app on mac os (more than 30000). However, providing IG as a desktop version for Windows or Linux is definitely not in scope. BUT, for that we have implemented the webapp as an installable progressive web app (PWA). Sadly, we don't have any numbers on how many people actually install the app, but guessing from our target groups technical capabilities I'd say there are maybe a few 100 who installed IG as PWA. 
Imo this feature could be made more visible to make IG more comfortable to use and also increase the visibility of IG in the daily live of our target group. @hauf-toni f

> [!Note]
> Installing PWAs does not work natively in firefox anymore. You need an extension for that.

**Describe the solution you'd like**
Create a custom install prompt that is more visible than before.
An example of how to implement this and how this looks can be found here https://microsoftedge.github.io/Demos/#progressive-web-apps-pwas (pwamp)

**Describe alternatives you've considered**
Not changing anything.

**Additional context**
Want to learn more about progressive web apps? -> https://web.dev/learn/pwa

**Comment by steffenkleinle** [comment]
Won't do, we don't see the need for this or any real benefit of it.
