### ISSUE TITLE
Push notifications on iOS 17.2 not received

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2655]
### Describe the Bug

A few users including @nassabay are reporting problems with receiving push notifications on iOS 17.2. Apparently on e.g. iOS 15.7 and on android devices everything is working as expected.

### Steps to Reproduce

1. Go to the CMS
2. Ensure the app city and language match the ones in the CMS (and that push notifications are enabled)
3. Close or put the app in the background on a device with iOS 17.2
4. Send a push notification
5. No push notification received

### Expected Behavior

I get a push notification.

### Actual Behavior

I don't get a push notification.

### Additional Information

<details>
  <summary>Reproduction:</summary>

Nachricht angekommen:
Softwareversion: 15.7.9
iPhone 7+

Nicht angekommen:
Softwareversion: 17.2.1
iPhone SE
(hier habe ich 2 Geräte zu Hause.  In keine von beiden ist die Nachricht angekommen.   
</details>

**Comment by LeandraH** [comment]
The app isn't even asking permission to send notifications anymore. There seems to be a new key `NSUserNotificationsUsageDescription` for the Info.plist for notifications but that should be available above iOS 15.4, so it wouldn't explain the notifications being received on Salua's iPhone 7+ with iOS 15.7.9. (https://forums.developer.apple.com/forums/thread/708259)

When running the app locally on my iPhone, I'm getting this error but I don't know if this is old or new:
`8.15.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '164298278764'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.`

**Comment by f1sh1918** [comment]
on ios 17.0.x everything works fine. This error also applies on `iOS17.3`

**Comment by f1sh1918** [comment]
> I just tried to receive a notification on emulated iOS 17.2 and did not receive anything.

on real device i received. i don't think this relies on the version but seem to be a general simulator problem

**Comment by LeandraH** [comment]
Great.

**Comment by steffenkleinle** [comment]
@f1sh1918 probably we can fix this issue with your [fix](#2680) for #2678 right?
