### ISSUE TITLE
Improve the user journey for a language change 

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2656]
**Is your feature request related to a problem? Please describe.**
From the municipality survey it was mentioned that users struggle with finding the possibilty to change the language inside the app.

**Describe the solution you'd like**
Possibly the icon should be re-evaluated?

**Describe alternatives you've considered**
Add lanugage changes to the context menu?!

**Comment by hauf-toni** [comment]
#2549

**Comment by sarahsporck** [comment]
As @hauf-toni already wrote this duplicates a ticket therefore this will be closed.
