### ISSUE TITLE
Replace Icon for "Behörde/Amt" in our POI categories

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2657]
**Is your feature request related to a problem? Please describe.**
The current icon is a hammer which is related negatively.

**Describe the solution you'd like**
Use another "more friendly" icon for Behörde/Amt

**Comment by hauf-toni** [comment]
<img width="200" alt="Bildschirmfoto 2024-02-05 um 13 04 46" src="https://github.com/digitalfabrik/integreat-app/assets/123894307/4464ef8f-a32f-48a9-bde9-76c778f38bd4">
<img width="200" alt="Bildschirmfoto 2024-02-05 um 13 13 53" src="https://github.com/digitalfabrik/integreat-app/assets/123894307/5318c8ef-0358-4278-a2a7-dbf19683d8c7">

Hier zwei Vorschläge (das Fax-gerät ist nicht ganz ernst gemeint, obwohl das wohl recht intuitiv funktionieren könnte 😄)

**Comment by hauf-toni** [comment]
🔗 [🏢 Figma File](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=2281%3A55&mode=design&t=FmgxUnM5sN7clJYm-1)

**Comment by ztefanie** [comment]
@vthejay @osmers @nassabay Bitte gerne kurz euren Input welches Icon ihr vermutet, dass von den Kommunen bevorzugt wird.

**Comment by sarahsporck** [comment]
@hauf-toni the icon should is used in the poi category filter. Therefore, the current suggestion is not suitable. Sorry for the miscommunitcation. See here


![Image](https://github.com/digitalfabrik/integreat-app/assets/28013368/37ab35bf-7e3b-4cc7-904f-0c4cf140beef)

**Comment by hauf-toni** [comment]
[🏣 Old icon in new format](https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=1136%3A3404&mode=design&t=rU9bMeoZmUKFKJPt-1)

**Comment by LeandraH** [comment]
Damn. This has to be done in the CMS code. Closing this issue in favour of the linked CMS one.
