### ISSUE TITLE
Error when deep linking to another city on ios

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2665]
### Describe the Bug

On ios when I deep link to another city an error is sent to sentry. I think we try to open the in-app browser twice.

### Steps to Reproduce

1. Go to 'Augsburg Stadt/Willkommen'
2. Deep link with `npx uri-scheme open integreat://integreat.app/testumgebung/de/willkommen/bei-uns/stadtplan --ios ` 
3. See the following
    1. A web view is opened
    2. The app navigates to the Dashboard page (as the deep link leads to an error)

### Expected Behavior

The web view is opened and the app does **not** navigate to the Dashboard Page. Also, no error is reported.

### Actual Behavior

The app navigates to the Dashboard page and an error is reported.

### Additional Information

See corresponding [sentry issue](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/3807/events/5f20f0078dcf4641a016aacfca68269f/).

**Comment by steffenkleinle** [comment]
Possibly related: https://github.com/digitalfabrik/integreat-app/issues/1922
We attempted to fix the same issue there.
