### ISSUE TITLE
Fix promote ios error

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2666]
The pipeline is failing for the ios promotion jobs in ~50% of the runs, with this error 
`Cannot update languages - could not find an editable version for 'IOS'`

See [here](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/10653/workflows/4b0f915e-1b9c-440b-9c68-eee34a0178e8/jobs/58796)

Expected behaviour: The pipeline should finish without errors.

**Additional context**
- Maybe this is helpful: https://github.com/fastlane/fastlane/issues/16991#issuecomment-692188666
- Keep in mind that this error only occurs on the first run, if you retry it succeeds.

Should be fixed by upgrading fastlane to [v2.222.0](https://github.com/fastlane/fastlane/releases/tag/2.220.0).

Related: #2698. The CI also fails there.

**Comment by steffenkleinle** [comment]
According to https://github.com/fastlane/fastlane/pull/21742, this is caused by degraded apple servers. The linked PR tries to mitigate the issue, wasn't released yet. Therefore I'd say that we have to wait until a new fastlane release is done.
