### ISSUE TITLE
INTEGREAT-APP-503: Crash on iOS mobile (chrome & google)

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2667]
### Describe the Bug

There have been more than 500 events of this crash which fails with a stack trace of `bb` when visiting [https://integreat.app/muenchen/en/everyday-life/mobility-2/car-driving](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/?project=2&query=is%3Aunresolved%20url%3A%22https%3A%2F%2Fintegreat.app%2Fmuenchen%2Fen%2Feveryday-life%2Fmobility-2%2Fcar-driving%22&referrer=event-tags&statsPeriod=14d&stream_index=4) on iOS mobile. Maybe it's also the page that throws the error in the browser. Then we'd need to inform the service team to inform the city.

### Steps to Reproduce

See sentry https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/5379/?project=2&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4
It seems to be related to translating the page with google.

**Comment by LeandraH** [comment]
This has last happened two months ago. Decent chance that a change in content fixed it.
