### ISSUE TITLE
NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2673]
**Is your feature request related to a problem? Please describe.**
All packages using the ip package should be updated, so the ip package version is > (greater not greater equal!) 2.0.0

**Additional context**
See here: https://github.com/digitalfabrik/integreat-app/security/dependabot/149
Packages that need updates are:
```
   - Hoisted from "_project_#native#react-native#@react-native-community#cli#@react-native-community#cli-doctor#ip"
   - Hoisted from "_project_#native#react-native#@react-native-community#cli#@react-native-community#cli-hermes#ip
```
Use `yarn why ip` to check if all occurences are updated correctly.

**Comment by LeandraH** [comment]
From https://github.com/react-native-community/cli/issues/2294 : FYI, the only affected command is profile-hermes when producing source maps. If you're not using it on a server (e.g. your CI), you're safe to ignore this and wait for us to patch it once we have a proper solution. If you are using it however, please disable it temporarily.

We don't use profile-hermes as far as I can tell, so we should be able to just wait for them.
