### ISSUE TITLE
Embed declaration on accessibility (DOA) in integreat (app and web)

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2674]
**Is your feature request related to a problem? Please describe.**
Municipalities are forced from 2026 to embed a DOA into their web-offers (Erkärung der Barrierefreiheit EZB). 

**Describe the solution you'd like**
Embed the DOA the same way as the Data Privacy Declaration.

This means:
Add a new link to the footer linking to https://integreat-app.de/barrierefreiheit/. The text should read `Barrierefreiheit` and be added to translations.json.

**Comment by sarahsporck** [comment]
This should only be done for integreat?

**Comment by dkehne** [comment]
Yes for Integreat only at the moment. Aschaffenburg needs possibly another declaration. Malte is not forced to have it.

**Comment by steffenkleinle** [comment]
> Yes for Integreat only at the moment. Aschaffenburg needs possibly another declaration. Malte is not forced to have it.

@dkehne would it hurt just having it for malte and aschaffenburg as well?

**Comment by dkehne** [comment]
No, would not hurt at all.
