### ISSUE TITLE
No margin before export events button

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2686]
### Steps to Reproduce

1. Go to https://webnext.integreat.app/testumgebung/de/events/jeden-2-und-4-donnerstag
2. See no padding

### Expected Behavior

There should be a margin between the recurrences of the event and the export event button.

### Actual Behavior

No margin before export events button.

### Additional Information

None.

**Comment by RaturiAR7** [comment]
I would like to work on this.

**Comment by steffenkleinle** [comment]
> I would like to work on this.

Sure, go for it! :tada: Thanks, let us know if you need anything :)

**Comment by steffenkleinle** [comment]
@RaturiAR7 are you still working on this issue? Do you need any help?

**Comment by marko-ignjatovic** [comment]
@steffenkleinle is this one fixed? 

![image](https://github.com/digitalfabrik/integreat-app/assets/31371916/cbfa347b-f16f-4eb4-acaf-12b8d52feb3c)

**Comment by steffenkleinle** [comment]
> @steffenkleinle is this one fixed?
> 
> ![image](https://private-user-images.githubusercontent.com/31371916/336394448-cbfa347b-f16f-4eb4-acaf-12b8d52feb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTUxNDcsIm5iZiI6MTcxNzQ5NDg0NywicGF0aCI6Ii8zMTM3MTkxNi8zMzYzOTQ0NDgtY2JmYTM0N2ItZjE2Zi00ZWI0LWFjYWYtMTJiOGQ1MmZlYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZjM3ZGM4ZmY4MTRlN2MxZTI5MjNjYmViZGY1NTRiMTNmZTg5OTc5ZjkyY2UxY2EzOGJhOTJjOWRiNGJmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zC6wikL_Uwz3ZmCnIR7DsFLWJZBXrjOQ97ckcxFtS30)

Hey @marko-ignjatovic, thanks for having a look at our issues and contributing, that is very much appreciated!
Hmm, it seems like this still/only happens if the content is empty. See e.g. https://webnext.integreat.app/testumgebung/de/events/jeden-2-und-4-donnerstag compared to https://integreat.app/testumgebung/de/events/jeden-2-und-4-donnerstag.
So I'd say this is not yet fixed and we should handle this case as well.

**Comment by steffenkleinle** [comment]
Maybe we should add a padding/margin/gap below page details instead of above the button though as it looks okay with content.

**Comment by marko-ignjatovic** [comment]
@steffenkleinle I added dynamic padding bottom to the `Spacing` component which wraps `PageDetails`. It should be tested with a real data tho as I couldn't really find event which doesn't contain content at all as you showed on image above.

**Comment by steffenkleinle** [comment]
> @steffenkleinle I added dynamic padding bottom to the `Spacing` component which wraps `PageDetails`. It should be tested with a real data tho as I couldn't really find event which doesn't contain content at all as you showed on image above.

Thanks!

Interesting, [this link](https://webnext.integreat.app/testumgebung/de/events/jeden-2-und-4-donnerstag) doesn't produce the above result for you? Mind the `webnext.` subdomain.

**Comment by marko-ignjatovic** [comment]
@steffenkleinle with this link I can see, I actually couldn't find a way to test it locally on my machine

**Comment by LeandraH** [comment]
The webnext domain works against `https://cms-test.integreat-app.de/`. Decent chance that your local environment is against `https://cms.integreat-app.de/`, if you get a description under `http://localhost:9000/testumgebung/de/events/jeden-2-und-4-donnerstag`. To change the API, open the browser console in your local environment and put in `window.localStorage.setItem('api-url', 'https://cms-test.integreat-app.de')` in there and refresh. You should then be able to see the event without description so that you can also test it locally :)
