### ISSUE TITLE
Support embedded offer for appointment booking

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2699]
**Is your feature request related to a problem? Please describe.**
As a user I want to be able to use the Terminbuchungstool (appointment booking tool) as simple as possible and directly from the app.

**Describe the solution you'd like**
We need to support an embedded offer for the appointment booking tool.

~~:warning: Currently waiting for cms as this embedded offer is not existing yet.~~

Acceptance criteria:
- The category with the embedded offer is displayed normally (in this case probably as 1st level tile)
- Clicking on the category with the embedded offer opens the URL in the InAppBrowser (native) or navigates there (web)

**Describe alternatives you've considered**
None.

**Additional context**
This is a feature request by the maltesers for the malte app. It should work in integreat as well though.
Mattermost thread:
https://chat.tuerantuer.org/digitalfabrik/pl/zcrkyb141ff9mnuw4ojc11ba6e

**Testing information**
This can be tested using **malte** at http://localhost:9000/testumgebung/de.
Clicking on the tile `Terminbuchung` should open https://testumgebung.termine.malteapp.de. The website doesnt work though since no instance for `testumgebung` is set up. To see the real tool checkout https://soest.termine.malteapp.de
(please dont enter any data as it is probably production).

**Related Issues**
#2712, #2702

**Comment by steffenkleinle** [comment]
@dkehne is it sufficient to support the appointment booking offer on the first level (tiles)? Or do we need support in the category lists as well?

**Comment by dkehne** [comment]
Tough Question. We justed discussed tiles so if it can be triggered by clicking a first level icon it's sufficient.

But I cannot promise that the requirements can change over time...

**Comment by steffenkleinle** [comment]
> Tough Question. We justed discussed tiles so if it can be triggered by clicking a first level icon it's sufficient.
> 
> But I cannot promise that the requirements can change over time...

That is okay. We can add support for 2nd and 3rd level later if the requirement changes. Thanks :)
