### ISSUE TITLE
Support appointment booking link for POIs

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2701]
The CMS provides the option to add a appointment booking link next to the opening times of a POI.

The app should support that field/label by adding/showing the appointment-booking-link in the UI if it is maintained/filled.

Design might be needed first.

<img width="401" alt="terminvereinbarung" src="https://github.com/digitalfabrik/integreat-app/assets/4182469/16619d66-c43e-4487-adf5-d5c6db192bae">

**Comment by dkehne** [comment]
Why do we need discussion here @steffenkleinle ? CMS already delivers that field/data?

**Comment by steffenkleinle** [comment]
> Why do we need discussion here @steffenkleinle ? CMS already delivers that field/data?

No idea anymore. I guess this is ready.
