### ISSUE TITLE
Filter events by date

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2706]
**Is your feature request related to a problem? Please describe.**
Sometimes you ar just overwhelmed by the event list. There are soo many events :o. It would be nice to be able to filter for (past/future) events. We should implement an event filter by date.

**Describe the solution you'd like**
- there should be an event filter by date for web & native

**Describe alternatives you've considered**
N/A

**Additional context**
Design can be found here -> https://www.figma.com/file/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?type=design&node-id=2376-2&mode=design&t=zQ9GHEHM5S1I7sVe-0

**Comment by hauf-toni** [comment]
option B is approved by the service team, the issue can be implemented

**Comment by LeandraH** [comment]
Closing in favour of #2808 which is better formulated.
