### ISSUE TITLE
Support page based offer for Lehrstellenradar

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2712]
**Is your feature request related to a problem? Please describe.**
If the Offers-tab is removed municipalities need to embed the Lehrstellenradar offers to their content. 

The HWK-Lehrstellenradar is using Post-Variables (https://github.com/digitalfabrik/integreat-app/blob/fb5d913b2f5fe031c758f82ab3e7d5a1c38827f2/shared/api/mapping/__tests__/mapCategoryJson.spec.ts#L81-L90) so how can the configuration of the URL (to only show offers in/near the own region) be realized?

**Describe the solution you'd like**
It seems as we might need to embed the filling of the post variables and the URL https://www.lehrstellen-radar.de/5100,0,lsrlist.html somewhere (automatically) in the system. So it might make sense to offer HWK-Lehrstellenradar as an embedded offer which can be chosen in the backend

**Alternative Solutions**
Enable the municipalities to add the variables somehow...

**Related Issues**
#2702, #2699

**Comment by svenseeberg** [comment]
I think the task should be changed to migrate all offers to page based offers within the app (or at least support them as page based offers).

**Comment by steffenkleinle** [comment]
Won't do as we will only support offers with dedicated APIs or self-hosted offers going forward. Those are:
:white_check_mark: Sprungbrett
:white_check_mark: KursNET
✅ Appointment booking (malte)
✅ Help button (malte)
:x: IHK
:x: HWK
:x: SerloABC
