### ISSUE TITLE
Fix missing API Declaration

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2719]
**Is your feature request related to a problem? Please describe.**
We need to fix Missing API declaration for apple uploads. Must be merged till **01.05.2024** or we will not be able to publish Integerat on Apple.

**Describe the solution you'd like**
Include a NSPrivacyAccessedAPITypes array in your app’s privacy 
manifest to provide approved reasons for these APIs used by your app’s code

**Additional context**

> *ITMS-91053: Missing API declaration* - Your app’s code in the “Integreat” file 
references one or more APIs that require reasons, including the following API 
categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required 
at this time, starting May 1, 2024, when you upload a new app or app update, you 
must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to 
provide approved reasons for these APIs used by your app’s code. For more 
details about this policy, including a list of required reason APIs and approved 
reasons for usage, visit: 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

> *ITMS-91053: Missing API declaration* - Your app’s code in the “Integreat” file 
references one or more APIs that require reasons, including the following API 
categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is 
required at this time, starting May 1, 2024, when you upload a new app or app 
update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy 
manifest to provide approved reasons for these APIs used by your app’s code. For 
more details about this policy, including a list of required reason APIs and 
approved reasons for usage, visit: 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

> *ITMS-91053: Missing API declaration* - Your app’s code in the “Integreat” file 
references one or more APIs that require reasons, including the following API 
categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is 
required at this time, starting May 1, 2024, when you upload a new app or app 
update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy 
manifest to provide approved reasons for these APIs used by your app’s code. For 
more details about this policy, including a list of required reason APIs and 
approved reasons for usage, visit: 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

> *ITMS-91053: Missing API declaration* - Your app’s code in the “Integreat” file 
references one or more APIs that require reasons, including the following API 
categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is 
required at this time, starting May 1, 2024, when you upload a new app or app 
update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy 
manifest to provide approved reasons for these APIs used by your app’s code. For 
more details about this policy, including a list of required reason APIs and 
approved reasons for usage, visit: 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by LeandraH** [comment]
Fixed in #2772
