### ISSUE TITLE
Add linting rule to use only one style of typing arrays

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2731]
**Is your feature request related to a problem? Please describe.**
We have places where arrays are typed as `content[]` and others where they are typed as `Array<content>`. We should decide on one and implement a linting rule to enforce that
https://typescript-eslint.io/rules/array-type/ 

**Describe the solution you'd like**

- [x] Decide on how we want to type arrays: `content[]` should be used
- [ ] Add the linting rules
- [ ] Update existing types

**Describe alternatives you've considered**
Both cases are functionally equivalent so we could also leave it.

**Comment by steffenkleinle** [comment]
I guess lets vote on this one :)
- `content[]` :bread: 
- `Array<content>` :bullettrain_front: 
- I want to use both :shrug:

**Comment by ztefanie** [comment]
I vote for [], as this is just the short version and [] supports readonly type modifier.

**Comment by steffenkleinle** [comment]
Lets go for `content[]` as @f1sh1918 is also in favor of that. Any objections @LeandraH?

**Comment by LeandraH** [comment]
No, works for me
