### ISSUE TITLE
Language cannot be changed in news.

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2732]
### Describe the Bug

If you try to change the language in a news entry, the message 'No translation available' appears.

### Steps to Reproduce

1. Go to Testumgebung Regression (Deutsch)
2. Click on 'News'
3. Find 'Nachricht Regrssionstest'
4. Click on 'Continue'
5. Inside the message click on 'change language' ikon
6. View bottom message: 'No translation available'

### Expected Behavior

If a language change is not possible at this point, a corresponding message should be displayed or if a language change is possible, the change should proceed normally.

### Actual Behavior

Languge change is not possible and a misleading (wrong) message is shown.

### Additional Information

In Web-app the issue occurs accordingly

~~Blocked by CMS for local news: https://github.com/digitalfabrik/integreat-cms/issues/2707~~
Check the tunews api for tünews, but at least wasn't possible at the time implementing this.

**Comment by osmers** [comment]
I think this has to do with the firebase we use for notifications - it is known and I think currently not avoidable? But correct me if I'm wrong.

**Comment by Docmale** [comment]
If so, the massage should sound like 'Changing the language is not possible at this point' since translations are available.

**Comment by osmers** [comment]
I agree that it is very unfortunate, that you can only change the language in the news overview page and not in the specific news itself - not sure how to fix it though and where to place this message

**Comment by steffenkleinle** [comment]
Basically its a CMS problem not telling us what the translations are. The id of the news is language specific, therefore without a property telling us where to find the translation nothing we can do in the frontends.

**Comment by Docmale** [comment]
Can we just change the message to 'Changing the language if any is not possible at this point' ('Eine eventuelle Änderung der Sprache ist hier nicht möglich') so the user knows that there are probably translations?

**Comment by steffenkleinle** [comment]
> Can we just change the message to 'Changing the language if any is not possible at this point' ('Eine eventuelle Änderung der Sprache ist hier nicht möglich') so the user knows that there are probably translations?

Imo thats too complicated and even more confusing. We could not show disabled languages as currently discussed in #https://github.com/digitalfabrik/integreat-app/issues/2550.
