### ISSUE TITLE
Look into replacing react-native-keyboard-aware-scroll-view

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2743]
**Is your feature request related to a problem? Please describe.**
The library [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view) seems to not be maintained anymore. So far, we haven't had issues with it but at some point, we probably will.

**Describe the solution you'd like**
Find a currently maintained alternative. This could be a different package, or we could try getting the native KeyboardAvoidingView to work (which would be great because that would be one less package to maintain).

**Describe alternatives you've considered**
We could wait until it breaks.

**Comment by ztefanie** [comment]
Won't do as the current library works good enough, as there are no good alternatives at the moment.
