### ISSUE TITLE
Refresh in maps doesn't work

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2751]
### Describe the Bug

When I try to refrsh in maps by expanding the POIs list and pull (but not from top) refreshing is shown but new POI is still missing.

### Steps to Reproduce

0. Use an android device (on iOS pull to refresh just closes the bottom action sheet which should be okay behavior as well)
1. Go to 'maps'
2. Add a new Poi for this region in CMS
3. Try to refresh by pulling in map
4. Added POI is still missing

### Expected Behavior

A refresh should refresh all data regardless where refreshing is executed

### Additional Information

Web works fine
See diskussion in https://chat.tuerantuer.org/digitalfabrik/pl/8cpoki3k1fftur6q7tpr14kdno

**Comment by f1sh1918** [comment]
Couldn't build on ios
Can you pull to refresh on android emulator? For me it doesn't work
