### ISSUE TITLE
New language "Oromo" for Integreat

### ISSUE THREAD

**Issue by nassabay** [digitalfabrik/integreat-app#2752]
**Is your feature request related to a problem? Please describe.**
The city of Regensburg wants to support Oromo in the App. Oromo is a language that is spoken by 38 Million people, mostly in Ethiopia, Kenia and Somalia. 

Proposed URL Parameter: orm
BCP47 Tag: orm-om

**Comment by osmers** [comment]
@steffenkleinle I don't think I received translation files for Oromo yet, right?
@nassabay can you change the title of the issue to Oromo instead of Omoro and create the language for testing in the CMS and add it to Testumgebung?

**Comment by steffenkleinle** [comment]
> @steffenkleinle I don't think I received translation files for Oromo yet, right? @nassabay can you change the title of the issue to Oromo instead of Omoro and create the language for testing in the CMS and add it to Testumgebung?

@osmers can you just use the same translation file I created for Slovakian last week and just rename it? There are no differences there.

**Comment by steffenkleinle** [comment]
@nassabay @osmers do you know whether `Oromo` or `Afaan Oromoo` is the correct/more common name for this language? It would be nice if we could just use `Oromo` as it is shorter/one word to avoid confusion.

**Comment by osmers** [comment]
@steffenkleinle I don't know but from researching a bit it would seem that Afaan simply means language and is probably used to distinguish it from the population name. Like for Maori language their own name is te reo Maori to differentiate between the people Maori and the language Maori. Since in our context it is clear that it is a language maybe we can just use Oromo - question remains whehter it should be 2 Os or just one...
And quite a few other sources mention Oromiff(a) - but not sure what that means exactly...

**Comment by osmers** [comment]
File for translation is sent to the translation office, awaiting their offer now.

**Comment by steffenkleinle** [comment]
> @steffenkleinle I don't know but from researching a bit it would seem that Afaan simply means language and is probably used to distinguish it from the population name. Like for Maori language their own name is te reo Maori to differentiate between the people Maori and the language Maori. Since in our context it is clear that it is a language maybe we can just use Oromo - question remains whehter it should be 2 Os or just one... And quite a few other sources mention Oromiff(a) - but not sure what that means exactly...

My guess would be that its just one `o` and the second one is just in connection with other words. At least all articles I found write it with one `o`.
