### ISSUE TITLE
Replace or rewrite native modules

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2753]
**Is your feature request related to a problem? Please describe.**
We have two native react native modules in our codebase that haven't changed since the beginning of time. Look into replacing them with more modern approaches, e.g. a library.

**Describe the solution you'd like**
* Replace the `FetcherModule` with something more recent
* Replace the `NativeConstantsModule` with something more recent

**Describe alternatives you've considered**
* Rewrite in kotlin
* Leave them as is

**Additional context**

**Comment by steffenkleinle** [comment]
Perhaps we can also just keep them as long as we don't run into any problems/have concrete reasons to remove them. They were already rewritten in Kotlin in #2757 for Android. I think I'd close this except anybody wants to have a look?

**Comment by ztefanie** [comment]
:+1: for closing this
