### ISSUE TITLE
Do not show search results, when there is no search term yet

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2755]
**Is your feature request related to a problem? Please describe.**
From our target group research we got the feedback, that people get confused, when they open the search, by the "results".

**Describe the solution you'd like**
Do not show results, if the search term has zero length

**Describe alternatives you've considered**
No alternatives yet discussed. If you have another idea, it needs to be discussed with the target group team and with the ui team.

**Additional context**
https://webnext.integreat.app/augsburg/de/search

[See the issue in open project](https://openproject.tuerantuer.org/projects/community-feedback/work_packages/3234/activity)

**Comment by LeandraH** [comment]
Yes, that had already been changed at some point, I opened a bug ticket to hide the results in web again #2896

**Comment by steffenkleinle** [comment]
It is fixed and just wasn't promoted to production yet. See webnext/beta.
