### ISSUE TITLE
Upgrade react-native to v0.74

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2786]
**Is your feature request related to a problem? Please describe.**
A new react-native version got released. See the upgrade helper for necessary things to do:
https://react-native-community.github.io/upgrade-helper/?from=0.73.8&to=0.74.1&package=tuerantuer.app.integreat&name=Integreat

**Testing information**
Please test everything (the whole app) very thoroughly!

**Additional context**
~~Please check whether it is possible with this to upgrade to yarn v3: #2026.~~
Not possible, the high memory usage issue which would require use to upgrade our CI images still exists :/

**Comment by LeandraH** [comment]
Ideally, upgrade to 0.75, or if not possible, open an issue to do it.
