### ISSUE TITLE
Google play console account verification (September 19, 2024)

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2791]
We need to do the google play console account verification 

We can do this from September 19, 2024 (60 days before deadline), deadline is November 18, 2024.
Your deadline to complete account verification is November 18, 2024
Start account verifications in Play Console from September 19, 2024 (60 days before deadline)

We will need a DUNS number for this, and requesting on can take up to 30 days!

**If we do not complete the verifications by this date, our developer profile and apps will be removed from Google Play.**

go to: https://play.google.com/console/u/0/developers/5269030016285360668/contact-details
to finalize it.
We need a DUNS number for finishing it, I am already on getting one. DUNS number is now available, see in the comments of the linked open project ticket

Maybe fixed here: https://tasks.tuerantuer.org/projects/infra/work_packages/2715/activity?query_id=59
Will keep this issue as a reminder for us anyways, as this is really important.

**Comment by LeandraH** [comment]
We have the DUNS number, now just need to wait until 19 September.

**Comment by dkehne** [comment]
I have delivered everything. Now status is "Google is processing the information you provided"

**Comment by dkehne** [comment]
Okay, the information (DUNS, contact data) were approved. Next step is that we need to provide identify details (company + managing board identify cards). I have uploaded that as well. 

Now they messaged us "Google is verifying your identity. This may take a few days/weeks."

**Comment by steffenkleinle** [comment]
@ztefanie @dkehne so this is done and can be closed, right?
