### ISSUE TITLE
Remove space for non-existant icons in the subcategories

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2792]
**Is your feature request related to a problem? Please describe.**
We reserve space in the subcategories for icons even though there often aren't any.

![Image](https://github.com/digitalfabrik/integreat-app/assets/18513943/b89a3977-2f14-494d-a785-08bb6e664494)

**Describe the solution you'd like**
We only reserve space there if an icon exists. Toni agrees :)

![Image](https://github.com/digitalfabrik/integreat-app/assets/18513943/636012cc-9a0a-4c44-bb30-a4d810679411)

**Additional context**
This came up in the context of #2767

**Comment by steffenkleinle** [comment]
@LeandraH should this only be done for subcategory items? How about category list items and search list items?
