### ISSUE TITLE
Add full-screen intent permissions

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2810]
Promoting and delivering to google fails with this error: 
```Google Api Error: Invalid request - You must let us know whether your app uses any full-screen intent permissions```

See here: https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/11392/workflows/3414f63d-7f22-49dc-88cd-83a02670b31d/jobs/62106
and here: https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/11394/workflows/29f9679a-6dd0-4483-9f2d-cc3df9c78865/jobs/62139

Fix this error.

**Comment by steffenkleinle** [comment]
I just completed `Upcoming Restrictions on USE_FULL_SCREEN_INTENT permission for all of our apps` in the Google Play Console. Without this, publishing/updating of apps in Android is not possible anymore. Basically it is just the questionnaire shown in the screenshot about the core functionality of our apps. I ticked `Other` for all apps.

![Image](https://github.com/digitalfabrik/integreat-app/assets/29095487/a64342b2-8c43-4fa3-b86a-d48276cbc952)


> You are receiving this email because you are using the USE_FULL_SCREEN_INTENT permission in your app and there are upcoming platform changes you should be prepared for. To prevent ad spam and credential phishing, only apps that have calling or alarm functionalities will have the permission enabled by default. Otherwise, you must get user permission to use the USE_FULL_SCREEN_INTENT permission.

> The use of full-screen intent notifications is intended to share high-priority messages that require the user's immediate attention. All developers using this permission are required to complete the Play Console declaration starting May 31, 2024, to indicate if your app has a permitted core functionality and qualifies for default enablement of the USE_FULL_SCREEN_INTENT permission. Starting October 31, 2024, all apps that did not complete the declaration or have not been approved for default enablement, will need to surface a prompt to users to grant permission on new installs on devices running Android 14 or above,and adjust the app experience gracefully if permission is denied.
