### ISSUE TITLE
Fix screenshots for apple

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2811]
**Is your feature request related to a problem? Please describe.**
Newest integreat release was rejected due to wrong informations on the screenshots. See [here](https://appstoreconnect.apple.com/apps/1072353915/distribution/reviewsubmissions/details/4169418b-c2a5-418a-bb7a-331985c079a2)

> Review Environment
Submission ID: 4169418b-c2a5-418a-bb7a-331985c079a2
Review date: May 27, 2024
Version reviewed: 2024.5.1
Guideline 2.3.7 - Performance - Accurate Metadata
The app screenshots include references to the price of the app or the service it provides, which is not considered a part of these metadata items.
Next Steps
To resolve this issue, please remove any references to pricing from the app's screenshots, including any references to the app or service being free or discounted. If you would like to advertise changes to the app's price, consider including this information in the app description.
Resources
For information on how to revise the app name, please review [Renaming a Project or App](http://help.apple.com/xcode/mac/8.2/#/dev3db3afe4f).
Support
Reply to this message in your preferred language if you need assistance. If you need additional support, use the [Contact Us module](https://developer.apple.com/contact/topic/#!/topic/select).
Consult with fellow developers and Apple engineers on the [Apple Developer Forums](https://developer.apple.com/forums/).
Help improve the review process or identify a need for clarity in our policies by [suggesting guideline changes](https://developer.apple.com/contact/app-store/?topic=guideline).

**Describe the solution you'd like**
Fix the issue, by adding adjusted screenshots.

**Describe alternatives you've considered**
Contact apple support and convince them to accept the screenshots.

**Additional context**
Maybe we need help from uiux to create new screenshots

**Comment by hauf-toni** [comment]
New Screens can be found here: [Nextcloud](https://nextcloud.tuerantuer.org/index.php/apps/files/files/6464428?dir=/Projects/Integreat/I%205.%20Design%20and%20Graphics/I%205.3.%20Digital/I%205.3.10%20Store%20Content/Playstore_Screenshots%20Ordner/Austauschscreen%20mit%20%C3%9Cbersetzungen)

**Comment by hauf-toni** [comment]
I recreated the ipad screens - i couldn't replicate the colour gradient in the background exactly. the source file + the screens are available [here](https://nextcloud.tuerantuer.org/index.php/apps/files/files/6466394?dir=/Projects/Integreat/I%205.%20Design%20and%20Graphics/I%205.3.%20Digital/I%205.3.10%20Store%20Content/Playstore_Screenshots%20Ordner/Austauschscreen%20mit%20%C3%9Cbersetzungen/Ipad)

**Comment by nikolahoff** [comment]
@steffenkleinle does this work? Then I can export the others as well
![Uploading Playstore-Screenshot-Ipad-arab.jpg…]()

**Comment by nikolahoff** [comment]
![Uploading Playstore-Screenshot-Ipad-arab.jpg…]()

**Comment by nikolahoff** [comment]
![Playstore-Screenshot-Ipad-arab](https://github.com/digitalfabrik/integreat-app/assets/97434837/337782d4-bbc5-41f2-8713-0c94320193af)
