### ISSUE TITLE
Enable Github setting to build forked pull requests, with safeguards

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2818]
**Is your feature request related to a problem? Please describe.**
We sometimes have contributors who aren't part of the Digitalfabrik. They usually fork the repo and then open a PR from the fork. That is great, and we very much want to encourage that.

But in order to actually merge a PR from a fork, we have to create our own branch in original repo, cherry-pick the commits over, and then merge it. It would be much nicer if we could simply click a button in the PR and merge.

There is a setting that allows to do that ("Build forked pull requests") but it would mean that a malicious actor could create a lot of PRs from forks against our repo and drive up our CI costs. That's not great.

So we want to enable the setting but without the possibility of a bad actor bankrupting us. @svenseeberg suggested checking if we can manually add something like a label to run the CI to PRs that we want to run the CI on.

**Describe the solution you'd like**
When there is a PR from a fork from our repo, I want to be able to
- run the checks (this can currently be done with one click in the open PR)
- merge the PR with an easy GUI solution
- if we still need fancy steps, please document them

**Describe alternatives you've considered**
We could continue doing the cherry-picking. We could also, each time we want to merge a PR from a fork, enable that setting, merge the PR, and then disable the setting. That only works for people who have those permissions though (which I, for example, don't have).

**Additional context**
Mattermost conversation about the topic here:
https://chat.tuerantuer.org/digitalfabrik/pl/z1e518f7nirabcxkzo5b9e339h

**Comment by ztefanie** [comment]
We discussed this issue in the weekly right now, we decided to:
- enable the workflow for forks
- the workflow may need adjustments so it works without secrets
- we see no real risk right now of this being abused and cost us a lot of credits
