### ISSUE TITLE
Broken link 'Lehrstellenradar'

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2836]
### Describe the Bug

The link  'Lehrstellenradar' leads to an unformatted error message

### Steps to Reproduce

1. Be in the native app
2. Go to Augsburg
3. Go to Offers
4. Click on 'Lehrstellenradar'
5. View xml-file with_HTTP_METHOD_NOT_SUPPORTED

**Comment by steffenkleinle** [comment]
This can be rejected, it will be removed with #2467 anyway.
