### ISSUE TITLE
No tooltip when hovering over calendar icon in event list

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2845]
### Describe the Bug

When I go to the list of events, I have calendar icons on the right of each event. When hovering over that, I used to get a tooltip telling me what the icon means. That is currently not happening.

### Steps to Reproduce

1. Go to 'https://integreat.app/augsburg/de/events'
2. Hover over the first calendar icon <img width="28" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/18513943/4e20642f-2836-4840-a6ab-e7b68d05025f">
3. See no tooltip

### Expected Behavior

A tooltip pops up when I hover over the icon.

### Actual Behavior

No tooltip pops up.

**Comment by steffenkleinle** [comment]
@LeandraH is this fixed in #2847 as a side-effect of replacing our tooltip component with react-tooltip?

**Comment by LeandraH** [comment]
> @LeandraH is this fixed in #2847 as a side-effect of replacing our tooltip component with react-tooltip?

Yes, exactly. Sorry, hadn't linked it yet
