### ISSUE TITLE
Chat icon covers footer in small screens on rtl

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2849]
### Describe the Bug

When on a rtl language setting and in a mobile screen, the chat icon is horizontally centered instead of on the left, and thus covers the footer.

### Steps to Reproduce

1. Make your browser window small enough to see the mobile view
2. Go to 'http://localhost:9000/testumgebung/ar'
3. See that the chat icon is centered at the bottom
4. Scroll down to the footer
5. See that you can't click on the footer

### Expected Behavior

The icon should be on the left and the footer accessible.

### Actual Behavior

The icon is centered and the footer can't be clicked.

### Additional Information

![Image](https://github.com/digitalfabrik/integreat-app/assets/18513943/da827efe-1847-4029-96e8-1a161189defc)

**Comment by f1sh1918** [comment]
Additionally another small issues could be addressed like the `margin-left` on the button to a `margin-inline-start`
<img width="375" alt="image" src="https://github.com/digitalfabrik/integreat-app/assets/37902063/3c00a38d-a962-47a4-9bcf-b1182d40bca8">
