### ISSUE TITLE
POI filter is too long for display and no scrolling available

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2856]
### Describe the Bug
Opening the POI filter on 5,5" phone leads two categories to be cut (see screenshot) and it's not possible to scroll.

### Expected Behavior
Scrolling Option

### Actual Behavior

![signal-2024-07-23-105049](https://github.com/user-attachments/assets/e940f3d0-ab78-4362-a1f6-23ea74d6eb76)

**Comment by f1sh1918** [comment]
@dkehne can you provide some information about the location you use here. Would be easier to reproduce

**Comment by dkehne** [comment]
@f1sh1918 Munich City

**Comment by steffenkleinle** [comment]
Done in #2869.
