### ISSUE TITLE
POI filters: Button to only show currently open locations can be cut off

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2870]
### Describe the Bug

When opening the overlay for filtering POIs on my iPhone 13 Mini with the phone language being set to French, the toggle button to only show currently open locations is cut off.

### Steps to Reproduce

1. Be on a small device (in this example, an iPhone 13 Mini)
2. Set the device language to French
3. Go to Maps
4. Click on the button to open the filter overlay ('Filter les lieux')
5. See error

### Expected Behavior

The description of the button should have a line break if the button otherwise doesn't fit onto the page.

### Actual Behavior

The description is all on one line, so if the language is one that takes up more space, the toggle gets pushed off the page.

### Additional Information
![Capture d’écran   2024-08-06 à 12 09 48](https://github.com/user-attachments/assets/70b733a6-4dab-454d-8ab2-03066279ab0d)

**Comment by bahaaTuffaha** [comment]
This issue has been fixed at #2856 Tested on virtual device Android 4.65' screen

**Comment by bahaaTuffaha** [comment]
Mistaken the button cut off with the toggle button I will reopen this .. my bad😅
