### ISSUE TITLE
Localization Issues at poi filter

### ISSUE THREAD

**Issue by bahaaTuffaha** [digitalfabrik/integreat-app#2875]
### Describe the Bug

When I switched the system language to Arabic language I noticed that the working hours at the poi filter is on the left also the education button in the categories it's not in Arabic.

### Steps to Reproduce

1. Change the device language to Arabic.
2. Go to Map.
3. Click on Filter location

### Additional Information

![Screenshot_1723208616](https://github.com/user-attachments/assets/3aac5305-1e76-4b1e-81c2-cb7bf846e524)

<details>
  <summary>Traceback</summary>

```

```

</details>

**Comment by steffenkleinle** [comment]
Nice find! The missing translation for `Bildung`/`Education` is a CMS issue. Perhaps you could open an issue here: https://github.com/digitalfabrik/integreat-cms/issues
