### ISSUE TITLE
All possible results shown in search without query term

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2896]
### Describe the Bug

When opening the search in the web without entering a query, we get all possible search results. That shouldn't happen.

### Steps to Reproduce

1. Go to https://integreat.app/badkreuznach/de/search
2. Wait for the loading to be finished
3. See all possible results

### Expected Behavior

See no results

### Actual Behavior

See all results

**Comment by steffenkleinle** [comment]
This is already fixed on webnext/beta. Just wasn't promoted yet as I forgot to reenable it.

**Comment by LeandraH** [comment]
Ooooops 😅
