### ISSUE TITLE
Language change leads to error

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2911]
### Describe the Bug
This bug is non deterministic and does not always occure.
It is a cause for our E2E Tests to fail
It also happens on my Android real device with the latest Integreat version from the stores.

### Steps to Reproduce

1. Open App
2. Checkout Testumgebung E2E
3. Change language

Maybe you need to repeat step 3 multiple times, to reproduce this issue.

### Expected Behavior
Language Change should work.

### Actual Behavior
Error is displayed

### Additional Information
Failing E2E Tests

https://github.com/user-attachments/assets/70d20fea-b1c4-4c4c-8580-61b92e2ca6a2

**Comment by ztefanie** [comment]
Happens also for location change


https://github.com/user-attachments/assets/fa052b85-1c53-4039-86fd-adf338f88a4d

**Comment by steffenkleinle** [comment]
I was sadly not able to reproduce this and will therefore unassign myself again.

**Comment by steffenkleinle** [comment]
@ztefanie I just tried again and I was still not able to reproduce this. Could you perhaps test if this issue still persists? We also did not have failing e2e tests in a while, so this might actually be fixed by now?

**Comment by ztefanie** [comment]
Cannot be reproduced anymore
