### ISSUE TITLE
Malformed URL crashes the app

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2922]
### Describe the Bug

If a malformed path is opened, the app crashes.

### Steps to Reproduce

1. Go to https://integreat.app/lkmuenchen/ru/%D0%BF%D1%80%D0%B8%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%B2-%D0%B3%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D0
2. The app crashes

### Expected Behavior

The app to not crash and show an error.

### Actual Behavior

The app crashing.

### Additional Information

The following "url" already crashes before the app is even reached.
https://integreat.app/lkmuenchen/ru/%D0%BF%D1%80%D0%B8%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%B2-%D0%B3%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D0%...

Sentry Issue: [INTEGREAT-APP-51H](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/5450/?referrer=github_integration)

**Comment by steffenkleinle** [comment]
> @steffenkleinle I'm not sure if I understand this issue correctly. Opening the URL fails but that makes sense because it's cut off, so the formatting is broken.

Yes, it is not a valid link and wrongly cut off from a valid one. And while I don't expect the app to correctly resolve the url (impossible), I definitely think that the app should not just crash nevertheless.
Instead, the app should be error resistant and show an error and/or just ignore the wrong path and open the dashboard or the closest page.

> Is the linked Sentry issue the correct one? Because I don't see any connection between the Sentry issue and this one.

Seems like I linked the wrong issue and can't find the right one anymore, but shouldn't matter as it is easily reproducible.

**Comment by LeandraH** [comment]
Ah, I understand now, thanks for the explanation. I don't think we can do much about this error from our end since, as you pointed out, the error happens before the app even loads. This would have to be handled by the CMS. I guess we could ask the CMS team to forward to an error page for URLs that are poorly formatted?

**Comment by steffenkleinle** [comment]
> Ah, I understand now, thanks for the explanation :)
> 
> I don't think we can do much about this error from our end since, as you pointed out, the error happens before the app even loads. This would have to be handled by the CMS. I guess we could ask the CMS team to forward to an error page for URLs that are poorly formatted?

I think this is only the case for the second URL (i.e. [this one](https://integreat.app/lkmuenchen/ru/%D0%BF%D1%80%D0%B8%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%B2-%D0%B3%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D0%)). For the [first one](https://integreat.app/lkmuenchen/ru/%D0%BF%D1%80%D0%B8%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%B2-%D0%B3%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D0) it is the app that crashes.

**Comment by LeandraH** [comment]
I think the underlying issue here is that our URLs are extremely long, especially any that are not in Latin letters. I'm inclined to discuss at the next conference if we want to change something about that. What do you think?

**Comment by steffenkleinle** [comment]
> I think the underlying issue here is that our URLs are extremely long, especially any that are not in Latin letters. I'm inclined to discuss at the next conference if we want to change something about that. What do you think?

I am confident that that is not the reason. If you use a correct URL that is longer, the app does not crash. I created a small fix in #2941 that should fix this (i.e. the first URL) problem. I wouldn't put any more time into this to also fix the second URL on the server side.

**Comment by LeandraH** [comment]
Well, yes, but the reason that URLs get cut off is because they are very long and so they are shortened by some apps when pasted. Or do you see other reasons for why someone would be trying to open a URL that is cut off partway through?

**Comment by steffenkleinle** [comment]
> Well, yes, but the reason that URLs get cut off is because they are very long and so they are shortened by some apps when pasted. Or do you see other reasons for why someone would be trying to open a URL that is cut off partway through?

Ohh, now I got it, thanks for explaining an being patient here :pray: I was just focusing on the symptoms I guess, not on the original problem :D

Jep, that should probably be fixed as well, perhaps with a maximum slug length in the CMS? Proably we have to investigate reasonable maximum lengths and how encoding and things work there though. Can you open an issue for that perhaps?

**Comment by LeandraH** [comment]
Done :) https://github.com/digitalfabrik/integreat-cms/issues/3119
