### ISSUE TITLE
react-native-pdf sometimes crashes the app

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2923]
### Describe the Bug

We get sentry reports about the app crashing becaues of react-native-pdf sometimes.

Sentry Issue: [INTEGREAT-APP-6Z8](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/7495/?referrer=github_integration)

https://github.com/wonday/react-native-pdf/issues/796 seems to be the same issue with potential fixes/reproductions.
https://github.com/wonday/react-native-pdf/pull/852 might provide a solution, too.

### Steps to Reproduce

Reproduction needed.

### Expected Behavior

The app not to crash.

### Actual Behavior

The app crashes.

### Additional Information

None.

**Comment by bahaaTuffaha** [comment]
https://github.com/user-attachments/assets/a2ba300b-91a4-4fbe-b9d6-6a1467fec5e4

Reproduced by: Pressing back quickly before content is loaded

**Comment by steffenkleinle** [comment]
@bahaaTuffaha can you confirm that this is fixed with the latest react-native-pdf version (https://github.com/wonday/react-native-pdf/releases)?

**Comment by bahaaTuffaha** [comment]
> @bahaaTuffaha can you confirm that this is fixed with the latest react-native-pdf version ([v6.7.5](https://github.com/wonday/react-native-pdf/releases/tag/v6.7.5))? There still seems to be another issue that is sometimes appearing if multiple times closing pdfs really fast multiple times (see [wonday/react-native-pdf#830](https://github.com/wonday/react-native-pdf/issues/830)), but this should be okay as users should not be doing that. I would therefore close this issue.

Yes it loads faster that I can't reproduce this error... on the same emulator on android 33
