### ISSUE TITLE
[Chat] Polling leads to scrolling to the end of the chat

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2931]
### Describe the Bug

Due to our polling, the chat scrolls to the end of all messages which can be rather annoying if you are trying to read previous or long messages.

### Steps to Reproduce

1. Go to [testumgebung](https://integreat.app/testumgebung/de)
2. Click chat button
3. Start a new conversation with lengthy messages
4. Scroll up
5. See the chat scrolling down automatically

### Expected Behavior

The expected behavior is as follows:
- No scrolling happens if no new messages are received
- The chat scrolls to the top of the first new message if there are new messages
- The text area should not loose focus

### Actual Behavior

The chat always scrolls to the end.

### Additional Information

None.

**Comment by svenseeberg** [comment]
There is one other problem that is closely related: the text area looses focus when new messages are polled.
