### ISSUE TITLE
Version 2024.9.3 can't be updated by the playstore under Android 9

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2937]
### Describe the Bug
The current Version (2024.9.3) of Integreat, Malte and Hallo A. can't be updated via playstore under Android 9. Android 14 is not affected and installing via *.apk is also fine. Sometimes the update spinner is running for ever.

### Steps to Reproduce

1. Make shure your version is less than 2014.9.3 on Android 9
2. Try to update the app by clicking "update"
3. after spinner the app is not updated and button shows 'Update'

### Expected Behavior
App is updated

**Comment by ztefanie** [comment]
Android 9 is API level 28
Our minSdkVersion is 21

**Comment by Docmale** [comment]
I have an old Note 8 with Android 9 and an OnPlus3 with A9, both have the same effect.  I uninstall Integreat then reboot and then install V9.2 by apk and try to update to 9.3 via the Appstore

https://github.com/user-attachments/assets/13e4c137-7602-4871-9583-e0c2a6f17f2d

**Comment by Docmale** [comment]
After further tests I now strongly suspect that the error always occurs when I try to update from an apk-installed version via appstore to current version, since I tried to update from various older versions but had no problems updating my phone in the past. So "suspend" this bug till next week checking then the update by appstore.

**Comment by Docmale** [comment]
Version 2014.9.4 was updeted normally on my real device, so I close thisbug as "no bug"
