### ISSUE TITLE
Old icon for Behörde/Amt still shown on map

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-app#2940]
### Describe the Bug

The old icon for Behörde/Amt is still shown on the map. 

### Steps to Reproduce

1. Go to https://integreat.app/augsburg/de/locations?category=1
2. Zoom in
3. See that the icon on the map is still the hammer

### Expected Behavior

Icon shown on the map should be the building

### Actual Behavior

Icon shown on the map is still the hammer

### Additional Information

Old issue: https://github.com/digitalfabrik/integreat-app/issues/2657
Design: https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=1136-3404&node-type=frame&t=OfgTae7shTAdSJdk-0
CMS issue: https://github.com/digitalfabrik/integreat-cms/issues/2800

Icon should be what's seen in the top left, but is what's actually on the map.

![image](https://github.com/user-attachments/assets/469b725f-30f6-47c2-88cb-9d02021485c8)

**Comment by f1sh1918** [comment]
**Short explanation**
For icons on the map we use a separate repository that creates an IconSprite for performance reasons
https://github.com/digitalfabrik/integreat-maplibre-style
You can find there a general manual.
In this case you have to replace the old hammer svg icon for each color group by the new one that you probably get from cms or design team. Please ensure that the naming is still correct:
<name>_<color>.svg , f.e. `health_#3700D2.svg`

**Comment by ztefanie** [comment]
ok we are having dissens if this is a good first issue :D

**Comment by steffenkleinle** [comment]
> ok we are having dissens if this is a good first issue :D

Seems like it haha. But since @f1sh1918 wrote the following on mattermost, I guessed it would not be that easy or rather a good first issue, but I don't mind at all:

> Since this is not very handy to do i suggested to not change single icons but in a batch
