### ISSUE TITLE
[Chat] Distinguish automatic messages and counselor messages

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2945]
**Is your feature request related to a problem? Please describe.**
Our chat endpoint returns messages both automatically generated and written by counselors.
The user should be able to tell for each message if they are automatically or human written.

**Describe the solution you'd like**
TBD

Ideas: robot icon, text (e.g. `automatic answer`) to indicate this.

**Describe alternatives you've considered**
?

**Additional context**
The API response includes an `automatic_answer` property:
https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/api/v3/chat/zammad_api.py#L99

integreat-chat issue: https://github.com/digitalfabrik/integreat-chat/issues/14

**Comment by ztefanie** [comment]
@hauf-toni Can you share some thoughts what would be a good UI for this?

**Comment by nikolahoff** [comment]
@steffenkleinle as I can see it in the design there is already a differentiation between automatic and personal answer? ![Image](https://github.com/user-attachments/assets/c2657534-804e-4e4f-9e2b-2ec8a10a48f2)
![Image](https://github.com/user-attachments/assets/40915aac-f0bd-4271-bb0f-4a26af263c9b)

**Comment by steffenkleinle** [comment]
@svenseeberg do you think this is enough? I think we don't have actual images of counselors, do we?

**Comment by nikolahoff** [comment]
@steffenkleinle we could use an icon for a person instead.

**Comment by nikolahoff** [comment]
@steffenkleinle @ztefanie the icons for the chat bot are in figma. For the chatbot we only use the Logo-Icon [here](https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=2671-2781&t=ud1V5POFEDcJT1rz-1) and for the counselor-icon is [here](https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=3638-1150&t=ud1V5POFEDcJT1rz-1)

**Comment by ztefanie** [comment]
@steffenkleinle Do we know the name of the person answering the message?

**Comment by steffenkleinle** [comment]
> @steffenkleinle Do we know the name of the person answering the message?

I don't think so, no. Correct @svenseeberg?

**Comment by svenseeberg** [comment]
We know the name in theory. But I don't think that many regions would like to see the names of their employees in the chat. I think this is something we should implement later based on feedback and knowledge about the acceptance.
