### ISSUE TITLE
double tooltip for event frequency

### ISSUE THREAD

**Issue by hauf-toni** [digitalfabrik/integreat-app#2988]
### Describe the Bug

the tooltip is not displayed correctly when hovering over the icon for the event frequency (found on web desktop when browsing events in Munich, could be reproduced in Augsburg Stadt)

### Additional Information
<img width="249" alt="Bildschirmfoto 2024-11-11 um 17 42 33" src="https://github.com/user-attachments/assets/c48d6426-c565-4ef2-be55-cece6791c150">
(please ignore the "wiederholend" under the icon since it was only visible when I took the screenshot)

**Comment by bahaaTuffaha** [comment]
I think this same as [2934](https://github.com/digitalfabrik/integreat-app/issues/2934)

**Comment by ztefanie** [comment]
close as duplication of #2934
