### ISSUE TITLE
Reorder the icons in the header in native

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#3005]
**Is your feature request related to a problem? Please describe.**
Reorder the header/navigation items as follows:

1. map with locations
2. news
3. events

Connected issue for web: #2468

**Comment by steffenkleinle** [comment]
@LeandraH this should already be done in #2993, right?

**Comment by LeandraH** [comment]
Yup, sorry, I missed that you had done the native part in there!

**Comment by steffenkleinle** [comment]
Duplicates #2468
